TAGED: taged/application/script/ParseHnSHero.php File Reference
ParseHnSHero.php File Reference
Namespaces
TAGED
Variables
$File =$argv[1]
$FilenameItems = array ('a', 'b', 'c')
$TextToParse = file_get_contents ($File)
$Parser = new HnSHeroParser ($TextToParse, $FilenameItems)
Variable Documentation
$File
$File =$argv[1]
Definition at line 8 of file ParseHnSHero.php.
Referenced by AggregateList\__construct(), Analysis\create(), Analysis\formatResult(), Algo\generateList(), PageNewAggregate\handle(), PageHnSParse\show(), and PageCollParse\show().
$FilenameItems
$FilenameItems = array ('a', 'b', 'c')
Definition at line 12 of file ParseHnSHero.php.
Referenced by moveFile().
$Parser
$Parser = new HnSHeroParser ($TextToParse, $FilenameItems)
Definition at line 16 of file ParseHnSHero.php.
Referenced by moveFile(), PageHnSParse\parse(), and PageCollParse\parse().
$TextToParse
$TextToParse = file_get_contents ($File)
Definition at line 14 of file ParseHnSHero.php.
Referenced by CollParser\__construct(), HnSHeroParser\__construct(), HnSParser\__construct(), moveFile(), PageHnSParse\parse(), and PageCollParse\parse().