TAGED: PageChangeAggregate Class Reference
PageChangeAggregate Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const CHANGE_AGGREGATE = 'change_aggregate'
const CHANGE_PASSWORD = 'change_password'
const CHANGE_REQUEST = 'change_request'
const CHANGE_REL_COLS = 'change_relation_cols'
const CHANGE_MES_COLS = 'change_measure_cols'
const CHANGE_SUBMIT = 'change_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
Protected Attributes
$Request
$Password
$Aggregate
$AggregateObj
$AggregateListObj
$AggregateList
Detailed Description
Definition at line 8 of file PageChangeAggregate.class.php.
Constructor & Destructor Documentation
__construct()
PageChangeAggregate::__construct ($InputData = NULL)
Constructeur de la classe PageChangeAggregate.
Parameters
mixed $InputData Les données d'entrée pour la page.
Definition at line 45 of file PageChangeAggregate.class.php.
References $Data, and handle().
Member Function Documentation
handle()
PageChangeAggregate::handle ($Data) protected
Gère les actions de la page.
Parameters
array $Data Les données de la requête.
Definition at line 68 of file PageChangeAggregate.class.php.
References $Aggregate, $Data, $Password, and show().
Referenced by __construct().
show()
PageChangeAggregate::show () protected
Affiche le contenu de la page.
Definition at line 105 of file PageChangeAggregate.class.php.
References $Aggregate, $Password, and $Request.
Referenced by handle().
Member Data Documentation
$Aggregate
PageChangeAggregate::$Aggregate protected
Definition at line 157 of file PageChangeAggregate.class.php.
Referenced by handle(), and show().
$AggregateList
PageChangeAggregate::$AggregateList protected
Definition at line 178 of file PageChangeAggregate.class.php.
$AggregateListObj
PageChangeAggregate::$AggregateListObj protected
Definition at line 171 of file PageChangeAggregate.class.php.
$AggregateObj
PageChangeAggregate::$AggregateObj protected
Definition at line 164 of file PageChangeAggregate.class.php.
$Password
PageChangeAggregate::$Password protected
Definition at line 150 of file PageChangeAggregate.class.php.
Referenced by handle(), and show().
$Request
PageChangeAggregate::$Request protected
Definition at line 143 of file PageChangeAggregate.class.php.
Referenced by show().
CHANGE_AGGREGATE
const PageChangeAggregate::CHANGE_AGGREGATE = 'change_aggregate'
Constante représentant l'action "Modifier Aggregation".
Definition at line 13 of file PageChangeAggregate.class.php.
Referenced by PageNewAggregate\handle(), and PageGestAggregate\show().
CHANGE_MES_COLS
const PageChangeAggregate::CHANGE_MES_COLS = 'change_measure_cols'
Constante représentant l'action "Modifier les Colonnes de Mesure".
Definition at line 33 of file PageChangeAggregate.class.php.
CHANGE_PASSWORD
const PageChangeAggregate::CHANGE_PASSWORD = 'change_password'
Constante représentant l'action "Modifier Mot de passe".
Definition at line 18 of file PageChangeAggregate.class.php.
CHANGE_REL_COLS
const PageChangeAggregate::CHANGE_REL_COLS = 'change_relation_cols'
Constante représentant l'action "Modifier les Colonnes de Relation".
Definition at line 28 of file PageChangeAggregate.class.php.
CHANGE_REQUEST
const PageChangeAggregate::CHANGE_REQUEST = 'change_request'
Constante représentant l'action "Modifier la Requête".
Definition at line 23 of file PageChangeAggregate.class.php.
CHANGE_SUBMIT
const PageChangeAggregate::CHANGE_SUBMIT = 'change_submit'
Constante représentant l'action "Envoyer les Modifications".
Definition at line 38 of file PageChangeAggregate.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageChangeAggregate.class.php