TAGED: HnSHeroParser Class Reference
HnSHeroParser Class Reference
Public Member Functions
__construct ($TextToParse, $Parameters=array())
__destruct ()
__toString ()
parse ()
Parse (with PCRE) the $this->text member variable.
Public Attributes
const ITEM_NAME = 'itemname'
const ITEM_POS = 'itempos'
const ITEM_IMG = 'itemimg'
const ITEM_AFFIX = 'itemaffix'
Protected Member Functions
parseUser ($Matches)
parseUserDetails ($Matches)
parseHero ($Matches)
parseItems ($Matches)
parseItem ($Matches)
parseParams ($Matches)
parseActive ($Matches)
parseAct ($Matches)
parsePassive ($Matches)
parsePass ($Matches)
parseAttributes ($Matches)
parseAttrP ($Matches)
parseAttrS ($Matches)
parseAttrR ($Matches)
Protected Attributes
$CurrentItem
$ItemList
Private Member Functions
clean ()
Clean the $this->FullText member variable of all undesirables characters. Use because PCRE pattern modifier m (PCRE_MULTILINE) have to use "\n" characters in a subject string to match multiline group (particularly useful for lists).
Private Attributes
$FullText
$ProcessedText
$Game
Detailed Description
Definition at line 7 of file HnSHeroParser.class.php.
Constructor & Destructor Documentation
__construct()
HnSHeroParser::__construct ($TextToParse, $Parameters = array ())
Definition at line 21 of file HnSHeroParser.class.php.
References $TextToParse, clean(), Hero\setClass(), Hero\setRank(), Hero\setRift(), Hero\setServer(), Hero\setTime(), and Hero\setURL().
__destruct()
HnSHeroParser::__destruct ()
Definition at line 46 of file HnSHeroParser.class.php.
Member Function Documentation
__toString()
HnSHeroParser::__toString ()
Definition at line 50 of file HnSHeroParser.class.php.
clean()
HnSHeroParser::clean () private
Clean the $this->FullText member variable of all undesirables characters. Use because PCRE pattern modifier m (PCRE_MULTILINE) have to use "\n" characters in a subject string to match multiline group (particularly useful for lists).
Definition at line 63 of file HnSHeroParser.class.php.
Referenced by __construct().
parse()
HnSHeroParser::parse ()
Parse (with PCRE) the $this->text member variable.
Exceptions
Exception
Definition at line 72 of file HnSHeroParser.class.php.
References $ProcessedText, and Hero\getURL().
parseAct()
HnSHeroParser::parseAct ($Matches) protected
Definition at line 167 of file HnSHeroParser.class.php.
References Hero\addComp().
parseActive()
HnSHeroParser::parseActive ($Matches) protected
Definition at line 160 of file HnSHeroParser.class.php.
parseAttributes()
HnSHeroParser::parseAttributes ($Matches) protected
Definition at line 197 of file HnSHeroParser.class.php.
parseAttrP()
HnSHeroParser::parseAttrP ($Matches) protected
Definition at line 206 of file HnSHeroParser.class.php.
References Hero\setAttr().
parseAttrR()
HnSHeroParser::parseAttrR ($Matches) protected
Definition at line 220 of file HnSHeroParser.class.php.
References Hero\setAttr().
parseAttrS()
HnSHeroParser::parseAttrS ($Matches) protected
Definition at line 213 of file HnSHeroParser.class.php.
References Hero\setAttr().
parseHero()
HnSHeroParser::parseHero ($Matches) protected
Definition at line 115 of file HnSHeroParser.class.php.
References Hero\setHeroname(), Hero\setLevel(), and Hero\setParangon().
parseItem()
HnSHeroParser::parseItem ($Matches) protected
Definition at line 135 of file HnSHeroParser.class.php.
References Hero\addItem().
parseItems()
HnSHeroParser::parseItems ($Matches) protected
Definition at line 128 of file HnSHeroParser.class.php.
parseParams()
HnSHeroParser::parseParams ($Matches) protected
Definition at line 152 of file HnSHeroParser.class.php.
References Hero\addAffix().
parsePass()
HnSHeroParser::parsePass ($Matches) protected
Definition at line 186 of file HnSHeroParser.class.php.
References Hero\addComp().
parsePassive()
HnSHeroParser::parsePassive ($Matches) protected
Definition at line 179 of file HnSHeroParser.class.php.
parseUser()
HnSHeroParser::parseUser ($Matches) protected
Definition at line 91 of file HnSHeroParser.class.php.
parseUserDetails()
HnSHeroParser::parseUserDetails ($Matches) protected
Definition at line 101 of file HnSHeroParser.class.php.
References Hero\getPlayer(), and Hero\setURL().
Member Data Documentation
$CurrentItem
HnSHeroParser::$CurrentItem protected
Definition at line 13 of file HnSHeroParser.class.php.
$FullText
HnSHeroParser::$FullText private
Definition at line 9 of file HnSHeroParser.class.php.
$Game
HnSHeroParser::$Game private
Definition at line 11 of file HnSHeroParser.class.php.
$ItemList
HnSHeroParser::$ItemList protected
Definition at line 14 of file HnSHeroParser.class.php.
$ProcessedText
HnSHeroParser::$ProcessedText private
Definition at line 10 of file HnSHeroParser.class.php.
Referenced by parse().
ITEM_AFFIX
const HnSHeroParser::ITEM_AFFIX = 'itemaffix'
Definition at line 19 of file HnSHeroParser.class.php.
ITEM_IMG
const HnSHeroParser::ITEM_IMG = 'itemimg'
Definition at line 18 of file HnSHeroParser.class.php.
ITEM_NAME
const HnSHeroParser::ITEM_NAME = 'itemname'
Definition at line 16 of file HnSHeroParser.class.php.
ITEM_POS
const HnSHeroParser::ITEM_POS = 'itempos'
Definition at line 17 of file HnSHeroParser.class.php.
The documentation for this class was generated from the following file:
taged/application/src/parse/HnSHeroParser.class.php