TAGED: M3Stroke Class Reference
M3Stroke Class Reference
Public Member Functions
__construct ($IDStroke=0, $StrokeNum=0, $Duration=0, $Time=0, $Matches=array())
__destruct ()
__toString ()
getNum ()
save ($IDGame=0)
Static Public Member Functions
static build ($Array)
Public Attributes
const TABLE = 'coup'
const ID = 'id_coup'
const NUM = 'num_coup'
const DURATION = 'duree'
const TIME = 'heure'
const WS_STROKE_NUM = 'stroke_num'
const WS_DURATION = 'duration'
const WS_TIME = 'time'
const WS_MATCH = 'match'
Protected Member Functions
addMatch ($MatchData=array())
fill ()
Protected Attributes
$IDStroke
$StrokeNum
$Duration
$Time
$Matches
Private Member Functions
fetchId ($IDGame)
Detailed Description
Definition at line 7 of file M3Stroke.class.php.
Constructor & Destructor Documentation
__construct()
M3Stroke::__construct ($IDStroke = 0, $StrokeNum = 0, $Duration = 0, $Time = 0, $Matches = array ())
Definition at line 29 of file M3Stroke.class.php.
References $Duration, $IDStroke, $Matches, $StrokeNum, $Time, addMatch(), and fill().
__destruct()
M3Stroke::__destruct ()
Definition at line 56 of file M3Stroke.class.php.
Member Function Documentation
__toString()
M3Stroke::__toString ()
Definition at line 60 of file M3Stroke.class.php.
addMatch()
M3Stroke::addMatch ($MatchData = array ()) protected
Definition at line 97 of file M3Stroke.class.php.
References M3Match\build().
Referenced by __construct().
build()
static M3Stroke::build ($Array) static
Definition at line 77 of file M3Stroke.class.php.
References $Duration, $Matches, $StrokeNum, and $Time.
Referenced by M3Game\addStroke().
fetchId()
M3Stroke::fetchId ($IDGame) private
Definition at line 114 of file M3Stroke.class.php.
References M3Game\ID_GAME.
Referenced by save().
fill()
M3Stroke::fill () protected
Definition at line 107 of file M3Stroke.class.php.
Referenced by __construct().
getNum()
M3Stroke::getNum ()
Definition at line 92 of file M3Stroke.class.php.
References $StrokeNum.
save()
M3Stroke::save ($IDGame = 0)
Definition at line 131 of file M3Stroke.class.php.
References fetchId(), and M3Game\ID_GAME.
Member Data Documentation
$Duration
M3Stroke::$Duration protected
Definition at line 23 of file M3Stroke.class.php.
Referenced by __construct(), and build().
$IDStroke
M3Stroke::$IDStroke protected
Definition at line 21 of file M3Stroke.class.php.
Referenced by __construct().
$Matches
M3Stroke::$Matches protected
Definition at line 25 of file M3Stroke.class.php.
Referenced by __construct(), and build().
$StrokeNum
M3Stroke::$StrokeNum protected
Definition at line 22 of file M3Stroke.class.php.
Referenced by __construct(), build(), and getNum().
$Time
M3Stroke::$Time protected
Definition at line 24 of file M3Stroke.class.php.
Referenced by __construct(), and build().
DURATION
const M3Stroke::DURATION = 'duree'
Definition at line 13 of file M3Stroke.class.php.
ID
const M3Stroke::ID = 'id_coup'
Definition at line 11 of file M3Stroke.class.php.
Referenced by M3Match\fetchId(), and M3Match\save().
NUM
const M3Stroke::NUM = 'num_coup'
Definition at line 12 of file M3Stroke.class.php.
TABLE
const M3Stroke::TABLE = 'coup'
Definition at line 9 of file M3Stroke.class.php.
TIME
const M3Stroke::TIME = 'heure'
Definition at line 14 of file M3Stroke.class.php.
WS_DURATION
const M3Stroke::WS_DURATION = 'duration'
Definition at line 17 of file M3Stroke.class.php.
WS_MATCH
const M3Stroke::WS_MATCH = 'match'
Definition at line 19 of file M3Stroke.class.php.
WS_STROKE_NUM
const M3Stroke::WS_STROKE_NUM = 'stroke_num'
Definition at line 16 of file M3Stroke.class.php.
WS_TIME
const M3Stroke::WS_TIME = 'time'
Definition at line 18 of file M3Stroke.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/Match3/M3Stroke.class.php