TAGED: CuboideEmergent Class Reference
CuboideEmergent Class Reference
Public Member Functions
computeCuboide ()
getID ()
getDataSet ()
getRowHeaders ()
getColIDs ()
isValid ()
__construct ($ColIDs, $Cuboide1, $Cuboide2)
computeCuboide ()
getDataSetFiltered ()
Public Member Functions inherited from Cuboide
__construct ($CuboideID, $RawDataSet, $RawRowHeaders, $RawColIDs, $MinMax=self::TO_MAX)
computeCuboide ()
Public Attributes
const CUBOIDE = 'CuboideBlocNestedLoop'
const CURRENT = ''
Public Attributes inherited from Cuboide
const TO_MAX = 'max'
const TO_MIN = 'min'
const TEST_ON = self::TO_MAX
const CURRENT = ''
Protected Member Functions
computeDataSet ($RawDataSet, $RawColIDs)
mergeColumns ()
mergeDataSets ()
mergeColumns ()
mergeDataSets ()
Protected Member Functions inherited from Cuboide
computeDataSet ($RawDataSet, $RawColIDs)
isInCuboide ($ConsideredRowID)
Protected Attributes
$Cuboide1
$Cuboide2
$FilteredDataSet
$ColIDsC1
$ColIDsC2
Protected Attributes inherited from Cuboide
$MinMax
Detailed Description
Definition at line 7 of file CuboideEmergentBlocNestedLoop.class.php.
Constructor & Destructor Documentation
__construct()
CuboideEmergent::__construct ($ColIDs, $Cuboide1, $Cuboide2)
CuboideEmergent constructor.
Parameters
array $ColIDs The column IDs of the Cuboide.
Cuboide $Cuboide1 The first Cuboide object.
Cuboide $Cuboide2 The second Cuboide object.
Definition at line 20 of file CuboideEmergent.class.php.
References $Cuboide1, $Cuboide2, mergeColumns(), and mergeDataSets().
Member Function Documentation
computeCuboide() [1/2]
CuboideEmergent::computeCuboide ()
Definition at line 83 of file CuboideEmergentBlocNestedLoop.class.php.
References mergeColumns(), and mergeDataSets().
computeCuboide() [2/2]
CuboideEmergent::computeCuboide ()
Computes the Cuboide for the Emergent Cuboide.
Definition at line 169 of file CuboideEmergent.class.php.
computeDataSet()
CuboideEmergent::computeDataSet ($RawDataSet, $RawColIDs) protected
Definition at line 11 of file CuboideEmergentBlocNestedLoop.class.php.
getColIDs()
CuboideEmergent::getColIDs ()
Definition at line 102 of file CuboideEmergentBlocNestedLoop.class.php.
getDataSet()
CuboideEmergent::getDataSet ()
Definition at line 96 of file CuboideEmergentBlocNestedLoop.class.php.
getDataSetFiltered()
CuboideEmergent::getDataSetFiltered ()
Gets the filtered data set of the Emergent Cuboide.
Returns
array The filtered data set.
Definition at line 184 of file CuboideEmergent.class.php.
References $FilteredDataSet.
getID()
CuboideEmergent::getID ()
Definition at line 94 of file CuboideEmergentBlocNestedLoop.class.php.
getRowHeaders()
CuboideEmergent::getRowHeaders ()
Definition at line 101 of file CuboideEmergentBlocNestedLoop.class.php.
isValid()
CuboideEmergent::isValid ()
Definition at line 103 of file CuboideEmergentBlocNestedLoop.class.php.
mergeColumns() [1/2]
CuboideEmergent::mergeColumns () protected
Merges columns from Cuboide1 and Cuboide2 to create the new set of column IDs.
Definition at line 42 of file CuboideEmergent.class.php.
mergeColumns() [2/2]
CuboideEmergent::mergeColumns () protected
Definition at line 44 of file CuboideEmergentBlocNestedLoop.class.php.
Referenced by __construct(), and computeCuboide().
mergeDataSets() [1/2]
CuboideEmergent::mergeDataSets () protected
Definition at line 65 of file CuboideEmergentBlocNestedLoop.class.php.
Referenced by __construct(), and computeCuboide().
mergeDataSets() [2/2]
CuboideEmergent::mergeDataSets () protected
Merges data sets from Cuboide1 and Cuboide2 to create the new data set.
Definition at line 87 of file CuboideEmergent.class.php.
References $FilteredDataSet.
Member Data Documentation
$ColIDsC1
CuboideEmergent::$ColIDsC1 protected
Definition at line 193 of file CuboideEmergent.class.php.
$ColIDsC2
CuboideEmergent::$ColIDsC2 protected
Definition at line 194 of file CuboideEmergent.class.php.
$Cuboide1
CuboideEmergent::$Cuboide1 protected
Definition at line 105 of file CuboideEmergentBlocNestedLoop.class.php.
Referenced by __construct().
$Cuboide2
CuboideEmergent::$Cuboide2 protected
Definition at line 106 of file CuboideEmergentBlocNestedLoop.class.php.
Referenced by __construct().
$FilteredDataSet
CuboideEmergent::$FilteredDataSet protected
Definition at line 189 of file CuboideEmergent.class.php.
Referenced by getDataSetFiltered(), and mergeDataSets().
CUBOIDE
const CuboideEmergent::CUBOIDE = 'CuboideBlocNestedLoop'
Definition at line 9 of file CuboideEmergentBlocNestedLoop.class.php.
CURRENT
const CuboideEmergent::CURRENT = ''
Definition at line 11 of file CuboideEmergent.class.php.
The documentation for this class was generated from the following files:
taged/application/old/CuboideEmergentBlocNestedLoop.class.php
taged/application/src/algo/CuboideEmergent.class.php