TAGED: Analysis Class Reference
Analysis Class Reference
Public Member Functions
__construct ($DescFile, $IsTest=FALSE)
prepare ()
cleanData ($Data)
compute ()
getResult ()
getAggregateFile ($AsNumerics=FALSE)
getRequestFile ()
getDBTable ()
getDBClass ()
getRelationCols ()
getMeasureCols ()
getSkyCube ()
setRequestFile ($NewValue)
setDBTable ($NewValue)
setDBClass ($NewValue)
setRelationCols ($NewValue)
setMeasureCols ($NewValue)
setMin ($NewValue)
setMax ($NewValue)
setAlgorithm ($Algo)
write ()
__construct ($DescFile)
run ($Algorithm, $M, $N)
formatResult ()
runSkyCube ($Algorithm, $M, $N, $MinMax=Cuboide::TO_MAX)
getSkyCubeColumns ()
getResult ()
getAggregateFile ($AsNumerics=FALSE)
getSkyCube ($AsNumerics=FALSE, $MinMax=Cuboide::TO_MAX, $Bidon=FALSE)
getRequestFile ()
getDBTable ()
getDBClass ()
getRelationCols ()
getMeasureCols ()
setRequestFile ($NewValue)
setDBTable ($NewValue)
setDBClass ($NewValue)
setRelationCols ($NewValue)
setMeasureCols ($NewValue)
write ()
Static Public Member Functions
static create ($Name, $Game, $RelationCols, $MeasureCols, $File=NULL, $Table=NULL)
static delete ($Name)
static create ($Name, $Game, $RelationCols, $MeasureCols, $File=NULL, $Table=NULL)
static delete ($Name)
Public Attributes
const DESC_FILE_PATH = '/chemin/vers/le/fichier_de_description.txt'
const DBCLASS = 'DbClass'
const TABLE = 'Table'
const FILE = 'File'
const REL_COLS = 'RelationCols'
const MES_COLS = 'MeasureCols'
const GAME_DB
Protected Member Functions
load ()
check ()
convertToNumerics ($Value, $Attribute)
computeCuboideAttribute ($CuboideID, $ColID, $Folder)
computeCuboide ($CuboideID, $Folder)
generateAlgoInput ()
getTestData ()
getTestMesCols ()
getTestRelCols ()
getTestMin ()
getTestMax ()
load ()
check ()
runCuboide ($Cuboide, $Algorithm, $M, $N)
getTestData ()
getTestMesCols ()
getTestRelCols ()
Static Protected Member Functions
static explodeCols ($Cols)
static explodeCols ($Cols)
Protected Attributes
$AttributeValues
$AttributeIgnored
$DescFile
$RequestFile
$DBTable
$DBClass
$RelationCols
$MeasureCols
$Runnable
$DescFilePath
$Algorithm
$DataSet
$SkyCube
$Min
$Max
$IsTest
$Result
Detailed Description
Definition at line 6 of file Analysis.class.php.
Constructor & Destructor Documentation
__construct() [1/2]
Analysis::__construct ($DescFile, $IsTest = FALSE)
Constructeur de l'analyse.
Parameters
string $DescFile Chemin vers le fichier de description.
bool $IsTest Indique si l'analyse est à des fins de test.
Definition at line 67 of file Analysis.class.php.
References $DescFile, $IsTest, and AGGREGATE_FOLDER_DESC.
__construct() [2/2]
Analysis::__construct ($DescFile)
Definition at line 21 of file Analysis_old.class.php.
References $DescFile, AGGREGATE_FOLDER_DESC, and load().
Member Function Documentation
check() [1/2]
Analysis::check () protected
Definition at line 51 of file Analysis_old.class.php.
check() [2/2]
Analysis::check () protected
Vérifie si l'analyse est prête pour le calcul.
Definition at line 132 of file Analysis.class.php.
Referenced by compute(), prepare(), and run().
cleanData()
Analysis::cleanData ($Data)
Nettoie les données en remplaçant les caractères spéciaux par des underscores.
Parameters
string $Data Les données à nettoyer.
Returns
string Les données nettoyées.
Definition at line 218 of file Analysis.class.php.
References $Data.
compute()
Analysis::compute ()
Effectue l'analyse en utilisant l'algorithme sélectionné.
Definition at line 415 of file Analysis.class.php.
References $Result, AGGREGATE_FOLDER_TMP, check(), computeCuboide(), and SkyCube\getCuboideIDs().
computeCuboide()
Analysis::computeCuboide ($CuboideID, $Folder) protected
Calcule le Cuboide complet et ses attributs.
Parameters
int $CuboideID L'ID du Cuboide.
string $Folder Le chemin du dossier.
Definition at line 315 of file Analysis.class.php.
References $Folder, computeCuboideAttribute(), and SkyCube\getCuboide().
Referenced by compute().
computeCuboideAttribute()
Analysis::computeCuboideAttribute ($CuboideID, $ColID, $Folder) protected
Calcule l'attribut Cuboide et définit le taux d'émergence dans SkyCube.
Parameters
int $CuboideID L'ID du Cuboide.
string $ColID L'ID de la colonne.
string $Folder Le chemin du dossier.
Definition at line 267 of file Analysis.class.php.
References $Folder, $Result, and SkyCube\getCuboide().
Referenced by computeCuboide().
convertToNumerics()
Analysis::convertToNumerics ($Value, $Attribute) protected
Convertit une valeur en numérique et conserve une correspondance des valeurs d'attribut.
Parameters
mixed $Value La valeur à convertir en numérique.
string $Attribute Le nom de l'attribut.
Returns
mixed La valeur numérique convertie.
Definition at line 230 of file Analysis.class.php.
References $Result.
create() [1/2]
static Analysis::create ($Name, $Game, $RelationCols, $MeasureCols, $File = NULL, $Table = NULL) static
Definition at line 331 of file Analysis_old.class.php.
References $DescFile, $File, $MeasureCols, $RelationCols, and AGGREGATE_FOLDER_REQUESTS.
create() [2/2]
static Analysis::create ($Name, $Game, $RelationCols, $MeasureCols, $File = NULL, $Table = NULL) static
Crée une nouvelle instance d'analyse avec les paramètres spécifiés et l'écrit dans le fichier de description.
Parameters
string $Name Le nom de l'analyse.
string $Game Le jeu pour lequel l'analyse est créée.
string $RelationCols Les colonnes utilisées pour les relations.
string $MeasureCols Les colonnes utilisées pour les mesures.
string | null $File Le chemin du fichier de requête.
string | null $Table Le nom de la table de base de données.
Definition at line 473 of file Analysis.class.php.
References $DescFile, $File, $MeasureCols, $RelationCols, and AGGREGATE_FOLDER_REQUESTS.
Referenced by PageNewAggregate\handle().
delete() [1/2]
static Analysis::delete ($Name) static
Definition at line 349 of file Analysis_old.class.php.
References $DescFile, $RequestFile, and AGGREGATE_FOLDER_DESC.
delete() [2/2]
static Analysis::delete ($Name) static
Supprime une instance d'analyse existante par son nom.
Parameters
string $Name Le nom de l'analyse à supprimer.
Definition at line 495 of file Analysis.class.php.
References $DescFile, $RequestFile, and AGGREGATE_FOLDER_DESC.
Referenced by PageGestAggregate\handle().
explodeCols() [1/2]
static Analysis::explodeCols ($Cols) static protected
Definition at line 81 of file Analysis_old.class.php.
References $Result.
explodeCols() [2/2]
static Analysis::explodeCols ($Cols) static protected
Explose une chaîne de colonnes en un tableau.
Parameters
string $Cols Les colonnes sous forme de chaîne séparée par des virgules.
Returns
array Les colonnes sous forme de tableau associatif.
Definition at line 111 of file Analysis.class.php.
References $Result.
formatResult()
Analysis::formatResult ()
Definition at line 158 of file Analysis_old.class.php.
References $File, $Result, and AGGREGATE_FOLDER_RESULTS.
generateAlgoInput()
Analysis::generateAlgoInput () protected
Génère l'entrée pour l'algorithme en traitant tous les Cuboides.
Definition at line 351 of file Analysis.class.php.
References SkyCube\getCuboide(), and SkyCube\getCuboideIDs().
getAggregateFile() [1/2]
Analysis::getAggregateFile ($AsNumerics = FALSE)
Definition at line 366 of file Analysis_old.class.php.
References AGGREGATE_FOLDER_REQUESTS.
getAggregateFile() [2/2]
Analysis::getAggregateFile ($AsNumerics = FALSE)
Definition at line 512 of file Analysis.class.php.
References AGGREGATE_FOLDER_REQUESTS.
Referenced by getSkyCube(), prepare(), and run().
getDBClass() [1/2]
Analysis::getDBClass ()
Definition at line 431 of file Analysis_old.class.php.
References $DBClass.
getDBClass() [2/2]
Analysis::getDBClass ()
Récupère le nom de la classe de base de données.
Returns
string Le nom de la classe de base de données.
Definition at line 678 of file Analysis.class.php.
References $DBClass.
getDBTable() [1/2]
Analysis::getDBTable ()
Definition at line 430 of file Analysis_old.class.php.
References $DBTable.
getDBTable() [2/2]
Analysis::getDBTable ()
Récupère le nom de la table de base de données.
Returns
string Le nom de la table de base de données.
Definition at line 672 of file Analysis.class.php.
References $DBTable.
getMeasureCols() [1/2]
Analysis::getMeasureCols ()
Definition at line 433 of file Analysis_old.class.php.
References $MeasureCols.
getMeasureCols() [2/2]
Analysis::getMeasureCols ()
Récupère les colonnes à mesurer pour l'analyse.
Returns
array Les colonnes à mesurer.
Definition at line 692 of file Analysis.class.php.
References $MeasureCols.
Referenced by getSkyCube(), and getSkyCubeColumns().
getRelationCols() [1/2]
Analysis::getRelationCols ()
Definition at line 432 of file Analysis_old.class.php.
References $RelationCols.
getRelationCols() [2/2]
Analysis::getRelationCols ()
Récupère les colonnes de relation pour l'analyse.
Returns
array Les colonnes de relation.
Definition at line 685 of file Analysis.class.php.
References $RelationCols.
Referenced by getSkyCube().
getRequestFile() [1/2]
Analysis::getRequestFile ()
Definition at line 429 of file Analysis_old.class.php.
References $RequestFile.
getRequestFile() [2/2]
Analysis::getRequestFile ()
Récupère le nom du fichier de requête.
Returns
string Le nom du fichier de requête.
Definition at line 666 of file Analysis.class.php.
References $RequestFile.
getResult() [1/2]
Analysis::getResult ()
Definition at line 326 of file Analysis_old.class.php.
References $Result.
getResult() [2/2]
Analysis::getResult ()
Obtient le résultat de l'analyse.
Returns
string Le résultat de l'analyse.
Definition at line 459 of file Analysis.class.php.
References $Result.
getSkyCube() [1/2]
Analysis::getSkyCube ($AsNumerics = FALSE, $MinMax = Cuboide::TO_MAX, $Bidon = FALSE)
Definition at line 405 of file Analysis_old.class.php.
References $DataSet, $SkyCube, getAggregateFile(), getMeasureCols(), getRelationCols(), getTestData(), getTestMesCols(), and getTestRelCols().
getSkyCube() [2/2]
Analysis::getSkyCube ()
Récupère le cube de données multidimensionnel SkyCube.
Returns
SkyCube Le cube de données multidimensionnel.
Definition at line 699 of file Analysis.class.php.
References $SkyCube.
Referenced by runSkyCube().
getSkyCubeColumns()
Analysis::getSkyCubeColumns ()
Definition at line 299 of file Analysis_old.class.php.
References getMeasureCols().
Referenced by runCuboide().
getTestData() [1/2]
Analysis::getTestData () protected
Definition at line 371 of file Analysis_old.class.php.
References $DataSet.
getTestData() [2/2]
Analysis::getTestData () protected
Récupère les données de test pour l'analyse.
Returns
array Les données de test sous forme de tableau.
Definition at line 522 of file Analysis.class.php.
References $DataSet.
Referenced by getSkyCube(), and prepare().
getTestMax()
Analysis::getTestMax () protected
Récupère les valeurs maximales pour chaque colonne.
Returns
array Les valeurs maximales par colonne.
Definition at line 655 of file Analysis.class.php.
Referenced by prepare().
getTestMesCols() [1/2]
Analysis::getTestMesCols () protected
Definition at line 382 of file Analysis_old.class.php.
getTestMesCols() [2/2]
Analysis::getTestMesCols () protected
Récupère les colonnes à mesurer dans les données de test.
Returns
array Les colonnes à mesurer.
Definition at line 614 of file Analysis.class.php.
Referenced by getSkyCube(), and prepare().
getTestMin()
Analysis::getTestMin () protected
Récupère les valeurs minimales pour chaque colonne.
Returns
array Les valeurs minimales par colonne.
Definition at line 645 of file Analysis.class.php.
Referenced by prepare().
getTestRelCols() [1/2]
Analysis::getTestRelCols () protected
Definition at line 396 of file Analysis_old.class.php.
getTestRelCols() [2/2]
Analysis::getTestRelCols () protected
Récupère les colonnes de relation dans les données de test.
Returns
array Les colonnes de relation.
Definition at line 630 of file Analysis.class.php.
Referenced by getSkyCube(), and prepare().
load() [1/2]
Analysis::load () protected
Definition at line 35 of file Analysis_old.class.php.
load() [2/2]
Analysis::load () protected
Charge les données à partir du fichier de description.
Definition at line 88 of file Analysis.class.php.
References $MeasureCols, and $RelationCols.
Referenced by __construct(), and prepare().
prepare()
Analysis::prepare ()
Prépare l'analyse en chargeant les données et en créant l'instance de SkyCube.
Definition at line 165 of file Analysis.class.php.
References $RelationCols, AGGREGATE_FOLDER_RESULTS, AGGREGATE_FOLDER_TMP, check(), getAggregateFile(), getTestData(), getTestMax(), getTestMesCols(), getTestMin(), getTestRelCols(), load(), and Cuboide\TO_MIN.
run()
Analysis::run ($Algorithm, $M, $N)
Definition at line 99 of file Analysis_old.class.php.
References $MeasureCols, $RelationCols, $Result, AGGREGATE_FOLDER_RESULTS, AGGREGATE_FOLDER_TMP, check(), and getAggregateFile().
runCuboide()
Analysis::runCuboide ($Cuboide, $Algorithm, $M, $N) protected
Definition at line 245 of file Analysis_old.class.php.
References $Data, $DataSet, and getSkyCubeColumns().
Referenced by runSkyCube().
runSkyCube()
Analysis::runSkyCube ($Algorithm, $M, $N, $MinMax = Cuboide::TO_MAX)
Definition at line 282 of file Analysis_old.class.php.
References $Algorithm, $SkyCube, getSkyCube(), and runCuboide().
setAlgorithm()
Analysis::setAlgorithm ($Algo)
Définit l'algorithme utilisé pour l'analyse.
Parameters
string $Algo Le nom de l'algorithme à utiliser.
Definition at line 755 of file Analysis.class.php.
References $Algo.
setDBClass() [1/2]
Analysis::setDBClass ($NewValue)
Definition at line 437 of file Analysis_old.class.php.
setDBClass() [2/2]
Analysis::setDBClass ($NewValue)
Définit le nom de la classe de base de données.
Parameters
string $NewValue Le nouveau nom de la classe de base de données.
Definition at line 720 of file Analysis.class.php.
setDBTable() [1/2]
Analysis::setDBTable ($NewValue)
Definition at line 436 of file Analysis_old.class.php.
setDBTable() [2/2]
Analysis::setDBTable ($NewValue)
Définit le nom de la table de base de données.
Parameters
string $NewValue Le nouveau nom de la table de base de données.
Definition at line 713 of file Analysis.class.php.
setMax()
Analysis::setMax ($NewValue)
Définit les valeurs maximales pour chaque colonne.
Parameters
array $NewValue Les nouvelles valeurs maximales par colonne.
Definition at line 748 of file Analysis.class.php.
setMeasureCols() [1/2]
Analysis::setMeasureCols ($NewValue)
Definition at line 439 of file Analysis_old.class.php.
setMeasureCols() [2/2]
Analysis::setMeasureCols ($NewValue)
Définit les colonnes à mesurer pour l'analyse.
Parameters
array $NewValue Les nouvelles colonnes à mesurer.
Definition at line 734 of file Analysis.class.php.
setMin()
Analysis::setMin ($NewValue)
Définit les valeurs minimales pour chaque colonne.
Parameters
array $NewValue Les nouvelles valeurs minimales par colonne.
Definition at line 741 of file Analysis.class.php.
setRelationCols() [1/2]
Analysis::setRelationCols ($NewValue)
Definition at line 438 of file Analysis_old.class.php.
setRelationCols() [2/2]
Analysis::setRelationCols ($NewValue)
Définit les colonnes de relation pour l'analyse.
Parameters
array $NewValue Les nouvelles colonnes de relation.
Definition at line 727 of file Analysis.class.php.
setRequestFile() [1/2]
Analysis::setRequestFile ($NewValue)
Definition at line 435 of file Analysis_old.class.php.
setRequestFile() [2/2]
Analysis::setRequestFile ($NewValue)
Définit le nom du fichier de requête.
Parameters
string $NewValue Le nouveau nom du fichier de requête.
Definition at line 706 of file Analysis.class.php.
write() [1/2]
Analysis::write ()
Definition at line 441 of file Analysis_old.class.php.
References $DBClass, $DBTable, $DescFile, $DescFilePath, $MeasureCols, $RelationCols, $RequestFile, and $Runnable.
write() [2/2]
Analysis::write ()
Écrit les paramètres d'analyse dans le fichier de description.
Definition at line 760 of file Analysis.class.php.
Member Data Documentation
$Algorithm
Analysis::$Algorithm protected
Definition at line 825 of file Analysis.class.php.
Referenced by runSkyCube().
$AttributeIgnored
Analysis::$AttributeIgnored protected
Definition at line 780 of file Analysis.class.php.
$AttributeValues
Analysis::$AttributeValues protected
Definition at line 775 of file Analysis.class.php.
$DataSet
Analysis::$DataSet protected
Definition at line 830 of file Analysis.class.php.
Referenced by getSkyCube(), getTestData(), and runCuboide().
$DBClass
Analysis::$DBClass protected
Definition at line 800 of file Analysis.class.php.
Referenced by getDBClass(), and write().
$DBTable
Analysis::$DBTable protected
Definition at line 795 of file Analysis.class.php.
Referenced by getDBTable(), and write().
$DescFile
Analysis::$DescFile protected
Definition at line 785 of file Analysis.class.php.
Referenced by __construct(), create(), delete(), and write().
$DescFilePath
Analysis::$DescFilePath protected
Definition at line 820 of file Analysis.class.php.
Referenced by write().
$IsTest
Analysis::$IsTest protected
Definition at line 850 of file Analysis.class.php.
Referenced by __construct().
$Max
Analysis::$Max protected
Definition at line 845 of file Analysis.class.php.
$MeasureCols
Analysis::$MeasureCols protected
Definition at line 810 of file Analysis.class.php.
Referenced by create(), getMeasureCols(), load(), run(), and write().
$Min
Analysis::$Min protected
Definition at line 840 of file Analysis.class.php.
$RelationCols
Analysis::$RelationCols protected
Definition at line 805 of file Analysis.class.php.
Referenced by create(), getRelationCols(), load(), prepare(), run(), and write().
$RequestFile
Analysis::$RequestFile protected
Definition at line 790 of file Analysis.class.php.
Referenced by delete(), getRequestFile(), and write().
$Result
Analysis::$Result protected
Definition at line 462 of file Analysis_old.class.php.
Referenced by compute(), computeCuboideAttribute(), convertToNumerics(), explodeCols(), formatResult(), getResult(), and run().
$Runnable
Analysis::$Runnable protected
Definition at line 815 of file Analysis.class.php.
Referenced by write().
$SkyCube
Analysis::$SkyCube protected
Definition at line 835 of file Analysis.class.php.
Referenced by getSkyCube(), and runSkyCube().
DBCLASS
const Analysis::DBCLASS = 'DbClass'
Clé pour la classe de base de données.
Definition at line 29 of file Analysis.class.php.
DESC_FILE_PATH
const Analysis::DESC_FILE_PATH = '/chemin/vers/le/fichier_de_description.txt'
Chemin du fichier de description.
Definition at line 24 of file Analysis.class.php.
FILE
const Analysis::FILE = 'File'
Clé pour le nom du fichier de requête.
Definition at line 39 of file Analysis.class.php.
GAME_DB
const Analysis::GAME_DB
Initial value:
= array (
        APP_NAME_COLLECTION   => 'TagedDBColl',
        APP_NAME_MATCH3       => 'TagedDBMatch3',
        APP_NAME_HACK_N_SLASH => 'TagedDBHnS'
    )
Tableau associatif contenant les noms de base de données du jeu.
Chaque clé représente le nom d'une application spécifique du jeu, et chaque valeur est le nom de la base de données correspondante.
Definition at line 56 of file Analysis.class.php.
MES_COLS
const Analysis::MES_COLS = 'MeasureCols'
Clé pour les colonnes à mesurer dans les données de test.
Definition at line 49 of file Analysis.class.php.
REL_COLS
const Analysis::REL_COLS = 'RelationCols'
Clé pour les colonnes de relation dans les données de test.
Definition at line 44 of file Analysis.class.php.
TABLE
const Analysis::TABLE = 'Table'
Clé pour le nom de la table de base de données.
Definition at line 34 of file Analysis.class.php.
The documentation for this class was generated from the following files:
taged/application/src/Analysis.class.php
taged/application/src/Analysis_old.class.php