TAGED: CollGame Class Reference
CollGame Class Reference
Public Member Functions
__construct ($IDCombat=-1, $Type='', $Gen='', $Tier='', $Rules='', $Result=0, $Rating='')
__destruct ()
__toString ()
showAsTableEntry ()
check ()
setID ($GameID)
setPlayer ($Player)
setTeam ($Team)
setType ($GameType)
setGen ($Gen)
setTier ($Tier)
setRated ($Message="")
setWinner ($Player)
setTie ()
addTurn ()
switch ($Player, $Pokemon)
save ()
Static Public Member Functions
static showTableHeader ()
static showTableFooter ()
Public Attributes
const TABLE = 'combat'
const VIEW = 'vw_equipe'
const TABLE_ENGAGE = 'engage'
const ID = 'id_combat'
const RESULT = 'resultat'
const GAGNANT = 'gagnant'
const TIER = 'tier'
const RULES = 'rules'
const CLASSE = 'classe'
const TURNS = 'tours'
Protected Member Functions
savePlayerEngaged ($Player, $Team, $Num)
saveGame ()
fill ()
Protected Attributes
$Player1
$Player2
$Team1
$Team2
$Result
$Tier
$Turns
$Rules
$Type
$Rating
$IDCombat
Detailed Description
Definition at line 7 of file CollGame.class.php.
Constructor & Destructor Documentation
__construct()
CollGame::__construct ($IDCombat = -1, $Type = '', $Gen = '', $Tier = '', $Rules = '', $Result = 0, $Rating = '')
Definition at line 36 of file CollGame.class.php.
References $IDCombat, $Rating, $Result, $Rules, $Tier, $Type, and fill().
__destruct()
CollGame::__destruct ()
Definition at line 64 of file CollGame.class.php.
Member Function Documentation
__toString()
CollGame::__toString ()
Definition at line 72 of file CollGame.class.php.
addTurn()
CollGame::addTurn ()
Definition at line 226 of file CollGame.class.php.
check()
CollGame::check ()
Definition at line 151 of file CollGame.class.php.
fill()
CollGame::fill () protected
Definition at line 346 of file CollGame.class.php.
References $Result, CollPlayer\AVATAR, CollTeam\DROP_RATE, CollTeam\ID, CollTeam\LISTE, CollPlayer\NOM, CollTeam\NOMBRE, CollPlayer\RATING, setPlayer(), and setTeam().
Referenced by __construct().
save()
CollGame::save ()
Definition at line 295 of file CollGame.class.php.
References saveGame().
saveGame()
CollGame::saveGame () protected
Definition at line 266 of file CollGame.class.php.
References savePlayerEngaged().
Referenced by save().
savePlayerEngaged()
CollGame::savePlayerEngaged ($Player, $Team, $Num) protected
Definition at line 243 of file CollGame.class.php.
References CollTeam\ID, CollPlayer\NOM, CollPlayer\NUMERO, CollPlayer\RATING, and CollPlayer\VICTOIRE.
Referenced by saveGame().
setGen()
CollGame::setGen ($Gen)
Definition at line 199 of file CollGame.class.php.
setID()
CollGame::setID ($GameID)
Definition at line 163 of file CollGame.class.php.
setPlayer()
CollGame::setPlayer ($Player)
Definition at line 169 of file CollGame.class.php.
Referenced by fill().
setRated()
CollGame::setRated ($Message = "")
Definition at line 209 of file CollGame.class.php.
setTeam()
CollGame::setTeam ($Team)
Definition at line 182 of file CollGame.class.php.
Referenced by fill().
setTie()
CollGame::setTie ()
Definition at line 221 of file CollGame.class.php.
setTier()
CollGame::setTier ($Tier)
Definition at line 204 of file CollGame.class.php.
References $Tier.
setType()
CollGame::setType ($GameType)
Definition at line 194 of file CollGame.class.php.
setWinner()
CollGame::setWinner ($Player)
Definition at line 215 of file CollGame.class.php.
showAsTableEntry()
CollGame::showAsTableEntry ()
Definition at line 116 of file CollGame.class.php.
showTableFooter()
static CollGame::showTableFooter () static
Definition at line 111 of file CollGame.class.php.
Referenced by Match3\show(), and CollTable\show().
showTableHeader()
static CollGame::showTableHeader () static
Definition at line 97 of file CollGame.class.php.
Referenced by Match3\show(), and CollTable\show().
switch()
CollGame::switch ($Player, $Pokemon)
Definition at line 231 of file CollGame.class.php.
Member Data Documentation
$IDCombat
CollGame::$IDCombat protected
Definition at line 32 of file CollGame.class.php.
Referenced by __construct().
$Player1
CollGame::$Player1 protected
Definition at line 21 of file CollGame.class.php.
$Player2
CollGame::$Player2 protected
Definition at line 22 of file CollGame.class.php.
$Rating
CollGame::$Rating protected
Definition at line 30 of file CollGame.class.php.
Referenced by __construct().
$Result
CollGame::$Result protected
Definition at line 25 of file CollGame.class.php.
Referenced by __construct(), and fill().
$Rules
CollGame::$Rules protected
Definition at line 28 of file CollGame.class.php.
Referenced by __construct().
$Team1
CollGame::$Team1 protected
Definition at line 23 of file CollGame.class.php.
$Team2
CollGame::$Team2 protected
Definition at line 24 of file CollGame.class.php.
$Tier
CollGame::$Tier protected
Definition at line 26 of file CollGame.class.php.
Referenced by __construct(), and setTier().
$Turns
CollGame::$Turns protected
Definition at line 27 of file CollGame.class.php.
$Type
CollGame::$Type protected
Definition at line 29 of file CollGame.class.php.
Referenced by __construct().
CLASSE
const CollGame::CLASSE = 'classe'
Definition at line 18 of file CollGame.class.php.
Referenced by Match3\getGames(), and CollTable\getGames().
GAGNANT
const CollGame::GAGNANT = 'gagnant'
Definition at line 15 of file CollGame.class.php.
ID
const CollGame::ID = 'id_combat'
Definition at line 13 of file CollGame.class.php.
Referenced by Match3\getGames(), and CollTable\getGames().
RESULT
const CollGame::RESULT = 'resultat'
Definition at line 14 of file CollGame.class.php.
Referenced by Match3\getGames(), and CollTable\getGames().
RULES
const CollGame::RULES = 'rules'
Definition at line 17 of file CollGame.class.php.
Referenced by Match3\getGames(), and CollTable\getGames().
TABLE
const CollGame::TABLE = 'combat'
Definition at line 9 of file CollGame.class.php.
Referenced by Match3\getGames(), and CollTable\getGames().
TABLE_ENGAGE
const CollGame::TABLE_ENGAGE = 'engage'
Definition at line 11 of file CollGame.class.php.
TIER
const CollGame::TIER = 'tier'
Definition at line 16 of file CollGame.class.php.
Referenced by Match3\getGames(), and CollTable\getGames().
TURNS
const CollGame::TURNS = 'tours'
Definition at line 19 of file CollGame.class.php.
VIEW
const CollGame::VIEW = 'vw_equipe'
Definition at line 10 of file CollGame.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/Coll/CollGame.class.php