TAGED: CollParser Class Reference
CollParser Class Reference
Public Member Functions
__construct ($TextToParse)
__destruct ()
parse ()
__toString ()
display ()
Protected Member Functions
applyPattern ($Pattern, $Callback, $Count=1)
gameIdPreg ($Match)
playerPreg ($Match)
teamSizePreg ($Match)
gameTypePreg ($Match)
genPreg ($Match)
tierPreg ($Match)
ratedPreg ($Match)
switchP1 ($Match)
switchP2 ($Match)
rulePreg ($Match)
teamPreviewPokemonPreg ($Match)
turnPreg ($Match)
move1Preg ($Match)
move2Preg ($Match)
winnerPreg ($Match)
tiePreg ($Match)
move1 ($pokemon, $move, $effect)
move2 ($pokemon, $move, $effect)
Private Member Functions
clean ()
Private Attributes
$turns
$FullText
$ProcessedText
$Game
Detailed Description
Definition at line 7 of file CollParser.class.php.
Constructor & Destructor Documentation
__construct()
CollParser::__construct ($TextToParse)
Construit un nouvel objet CollParser.
Parameters
string $TextToParse Le texte brut à analyser.
Definition at line 15 of file CollParser.class.php.
References $TextToParse, and clean().
__destruct()
CollParser::__destruct ()
Definition at line 23 of file CollParser.class.php.
Member Function Documentation
__toString()
CollParser::__toString ()
Convertit l'objet CollParser en une chaîne de caractères pour l'affichage.
Returns
string La représentation de l'objet sous forme de chaîne de caractères.
Definition at line 139 of file CollParser.class.php.
applyPattern()
CollParser::applyPattern ($Pattern, $Callback, $Count = 1) protected
Applique un motif (pattern) avec une fonction de rappel sur le texte traité.
Parameters
string $Pattern Le motif (pattern) d'expression régulière à appliquer.
string $Callback La fonction de rappel à appeler pour chaque correspondance.
int $Count Le nombre de fois que le motif doit être appliqué (facultatif, par défaut 1).
Definition at line 48 of file CollParser.class.php.
Referenced by parse().
clean()
CollParser::clean () private
Nettoie le contenu de $this->FullText de tous les caractères indésirables. Utilise le modificateur d'expression régulière m (PCRE_MULTILINE) pour utiliser des caractères "\n" dans une chaîne de sujet afin de faire correspondre des groupes multilignes (particulièrement utile pour les listes).
Definition at line 32 of file CollParser.class.php.
Referenced by __construct().
display()
CollParser::display ()
Affiche les informations analysées pour le débogage.
Cette méthode affiche les différentes propriétés et informations analysées par la classe pour le débogage. Elle permet de vérifier que les données ont été correctement extraites et organisées.
Definition at line 153 of file CollParser.class.php.
gameIdPreg()
CollParser::gameIdPreg ($Match) protected
Gère la description d'un Pokémon dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 189 of file CollParser.class.php.
gameTypePreg()
CollParser::gameTypePreg ($Match) protected
Gère la description du type de jeu (Game Type) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 241 of file CollParser.class.php.
genPreg()
CollParser::genPreg ($Match) protected
Gère la description de la génération (Gen) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 255 of file CollParser.class.php.
move1()
CollParser::move1 ($pokemon, $move, $effect) protected
Gère la description d'un mouvement (Move) d'un Pokémon dans le texte traité.
Parameters
string $pokemon Le nom du Pokémon.
string $move Le nom du mouvement (Move).
string $effect L'effet du mouvement (Move).
Definition at line 414 of file CollParser.class.php.
move1Preg()
CollParser::move1Preg ($Match) protected
Gère la description d'un mouvement (Move) lors d'un switch dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 361 of file CollParser.class.php.
move2()
CollParser::move2 ($pokemon, $move, $effect) protected
Gère la description d'un mouvement (Move) d'un Pokémon dans le texte traité.
Parameters
string $pokemon Le nom du Pokémon.
string $move Le nom du mouvement (Move).
string $effect L'effet du mouvement (Move).
Definition at line 426 of file CollParser.class.php.
move2Preg()
CollParser::move2Preg ($Match) protected
Gère la description d'un mouvement (Move) lors d'un switch dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 371 of file CollParser.class.php.
parse()
CollParser::parse ()
Analyse le texte traité (ProcessedText) avec des expressions régulières (PCRE).
Cette méthode parcourt le texte et utilise des motifs d'expression régulière pour extraire des informations spécifiques. Elle appelle les fonctions de rappel appropriées pour traiter les correspondances trouvées.
Exceptions
Exception En cas de problème lors de l'analyse.
Definition at line 66 of file CollParser.class.php.
References $ProcessedText, and applyPattern().
playerPreg()
CollParser::playerPreg ($Match) protected
Gère la description d'un joueur (Player) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 206 of file CollParser.class.php.
ratedPreg()
CollParser::ratedPreg ($Match) protected
Gère la description d'une partie notée (Rated) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 283 of file CollParser.class.php.
rulePreg()
CollParser::rulePreg ($Match) protected
Gère la description d'une règle (Rule) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Deprecated:
Definition at line 327 of file CollParser.class.php.
switchP1()
CollParser::switchP1 ($Match) protected
Gère la description d'un switch du joueur 1 (P1) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 298 of file CollParser.class.php.
switchP2()
CollParser::switchP2 ($Match) protected
Gère la description d'un switch du joueur 2 (P2) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 312 of file CollParser.class.php.
teamPreviewPokemonPreg()
CollParser::teamPreviewPokemonPreg ($Match) protected
Gère la description d'un Pokémon lors du choix des équipes (Team Preview) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Deprecated:
Definition at line 338 of file CollParser.class.php.
teamSizePreg()
CollParser::teamSizePreg ($Match) protected
Gère la description d'une équipe (Team) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 225 of file CollParser.class.php.
tiePreg()
CollParser::tiePreg ($Match) protected
Gère la description d'une égalité (Tie) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 395 of file CollParser.class.php.
tierPreg()
CollParser::tierPreg ($Match) protected
Gère la description du tier dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 269 of file CollParser.class.php.
turnPreg()
CollParser::turnPreg ($Match) protected
Gère la description d'un tour (Turn) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 348 of file CollParser.class.php.
winnerPreg()
CollParser::winnerPreg ($Match) protected
Gère la description du gagnant (Winner) dans le texte traité.
Parameters
array $Match Le tableau des arguments lus depuis le texte.
Definition at line 381 of file CollParser.class.php.
Member Data Documentation
$FullText
CollParser::$FullText private
Definition at line 440 of file CollParser.class.php.
$Game
CollParser::$Game private
Definition at line 450 of file CollParser.class.php.
$ProcessedText
CollParser::$ProcessedText private
Definition at line 445 of file CollParser.class.php.
Referenced by parse().
$turns
CollParser::$turns private
Definition at line 435 of file CollParser.class.php.
The documentation for this class was generated from the following file:
taged/application/src/parse/CollParser.class.php