TAGED: PageCollParse Class Reference
PageCollParse Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const PARSER_FILE = 'parser_file'
const PARSER_SUBMIT = 'parser_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
parse ()
Protected Attributes
$FileToParse
Detailed Description
Definition at line 8 of file PageCollParse.class.php.
Constructor & Destructor Documentation
__construct()
PageCollParse::__construct ($InputData = NULL)
Constructeur de la classe PageCollParse.
Parameters
mixed $InputData Les données d'entrée pour la page.
Definition at line 25 of file PageCollParse.class.php.
References $Data, and handle().
Member Function Documentation
handle()
PageCollParse::handle ($Data) protected
Gère le traitement des données d'entrée.
Parameters
mixed $Data Les données d'entrée pour la page.
Definition at line 42 of file PageCollParse.class.php.
References $Data, parse(), and show().
Referenced by __construct().
parse()
PageCollParse::parse () protected
Effectue l'opération de parsing.
Definition at line 78 of file PageCollParse.class.php.
References $Parser, and $TextToParse.
Referenced by handle().
show()
PageCollParse::show () protected
Affiche le contenu de la page.
Definition at line 67 of file PageCollParse.class.php.
References $File.
Referenced by handle().
Member Data Documentation
$FileToParse
PageCollParse::$FileToParse protected
Definition at line 105 of file PageCollParse.class.php.
PARSER_FILE
const PageCollParse::PARSER_FILE = 'parser_file'
Constante représentant le nom du champ de fichier de parsing.
Definition at line 13 of file PageCollParse.class.php.
PARSER_SUBMIT
const PageCollParse::PARSER_SUBMIT = 'parser_submit'
Constante représentant le nom du champ de soumission du formulaire.
Definition at line 18 of file PageCollParse.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageCollParse.class.php