TAGED: IDEA Class Reference
IDEA Class Reference
Public Member Functions
__construct ($Name, $Folder)
run ()
setAlgorithm ($NewValue)
setMeasures ($NewValue)
setRelations ($NewValue)
setMin ($NewValue)
setMax ($NewValue)
Protected Member Functions
prepare ()
prepareRelations ()
countAttributes ()
anonymize ()
prepareMeasures ()
prepareTupleFile ()
exportMeasures ()
exportRelations ()
computeMinMax ()
interpret ($Results)
convertToNumerics ($Value, $Attribute)
Protected Attributes
$Algorithm
$FilePath
$Min
$Max
$NbAttributes
$NbTuples
$InputMeasures
$InputRelations
$WIPMeasures
$WIPRelations
$PreparedMeasures
$PreparedRelations
$Attributes
$AttributeValues
$AttributeIgnored
Detailed Description
Definition at line 7 of file IDEA.class.php.
Constructor & Destructor Documentation
__construct()
IDEA::__construct ($Name, $Folder)
The constructor of the IDEA class.
Parameters
string $Name The name of the IDEA file.
string $Folder The folder where the IDEA file is located.
Definition at line 15 of file IDEA.class.php.
References $Folder.
Member Function Documentation
anonymize()
IDEA::anonymize () protected
Anonymizes the attribute values in the relations data.
Definition at line 97 of file IDEA.class.php.
References convertToNumerics().
Referenced by prepareRelations().
computeMinMax()
IDEA::computeMinMax () protected
Computes the minimum and maximum values for IDEA computation. If Min and Max values are not set, computes them from the input measures.
Definition at line 210 of file IDEA.class.php.
Referenced by prepare().
convertToNumerics()
IDEA::convertToNumerics ($Value, $Attribute) protected
Converts the given attribute value to a numeric representation.
Parameters
mixed $Value The attribute value to be converted.
string $Attribute The name of the attribute.
Returns
mixed The numeric representation of the attribute value.
Definition at line 280 of file IDEA.class.php.
References $Result.
Referenced by anonymize().
countAttributes()
IDEA::countAttributes () protected
Counts the number of attributes (columns) in the data set.
Definition at line 89 of file IDEA.class.php.
Referenced by prepareRelations().
exportMeasures()
IDEA::exportMeasures () protected
Exports the prepared measures data to a CSV file.
Definition at line 187 of file IDEA.class.php.
Referenced by prepare().
exportRelations()
IDEA::exportRelations () protected
Exports the prepared relations data to a CSV file.
Definition at line 198 of file IDEA.class.php.
Referenced by prepare().
interpret()
IDEA::interpret ($Results) protected
Interprets the IDEA results from the generated output file.
Parameters
string $Results The raw shell output from IDEA execution.
Returns
array An array representing the interpreted results.
Definition at line 222 of file IDEA.class.php.
References $Data, and $Result.
Referenced by run().
prepare()
IDEA::prepare () protected
Prepares the data for IDEA execution by calling various internal methods.
Definition at line 62 of file IDEA.class.php.
References computeMinMax(), exportMeasures(), exportRelations(), prepareMeasures(), prepareRelations(), and prepareTupleFile().
Referenced by run().
prepareMeasures()
IDEA::prepareMeasures () protected
Prepares the measures data for IDEA execution. Handles duplicating rows for multiple measures and value conversions.
Definition at line 119 of file IDEA.class.php.
References $InputMeasures.
Referenced by prepare().
prepareRelations()
IDEA::prepareRelations () protected
Prepares the relations data for IDEA execution. Handles anonymization, attribute counting, and value conversion.
Definition at line 77 of file IDEA.class.php.
References $InputRelations, anonymize(), and countAttributes().
Referenced by prepare().
prepareTupleFile()
IDEA::prepareTupleFile () protected
Prepares the tuple file required for IDEA execution.
Definition at line 175 of file IDEA.class.php.
Referenced by prepare().
run()
IDEA::run ()
Runs the IDEA program and interprets the results.
Returns
array An array representing the interpreted results.
Definition at line 43 of file IDEA.class.php.
References $Min, interpret(), and prepare().
setAlgorithm()
IDEA::setAlgorithm ($NewValue)
Sets the algorithm used by IDEA.
Parameters
string $NewValue The name of the algorithm.
Definition at line 316 of file IDEA.class.php.
setMax()
IDEA::setMax ($NewValue)
Sets the maximum value for IDEA computation.
Parameters
int | null $NewValue The maximum value for IDEA computation.
Definition at line 344 of file IDEA.class.php.
setMeasures()
IDEA::setMeasures ($NewValue)
Sets the input measures data for IDEA execution.
Parameters
array $NewValue An associative array representing input measures.
Definition at line 323 of file IDEA.class.php.
setMin()
IDEA::setMin ($NewValue)
Sets the minimum value for IDEA computation.
Parameters
int | null $NewValue The minimum value for IDEA computation.
Definition at line 337 of file IDEA.class.php.
setRelations()
IDEA::setRelations ($NewValue)
Sets the input relations data for IDEA execution.
Parameters
array $NewValue An associative array representing input relations.
Definition at line 330 of file IDEA.class.php.
Member Data Documentation
$Algorithm
IDEA::$Algorithm protected
Definition at line 349 of file IDEA.class.php.
$AttributeIgnored
IDEA::$AttributeIgnored protected
Definition at line 419 of file IDEA.class.php.
$Attributes
IDEA::$Attributes protected
Definition at line 409 of file IDEA.class.php.
$AttributeValues
IDEA::$AttributeValues protected
Definition at line 414 of file IDEA.class.php.
$FilePath
IDEA::$FilePath protected
Definition at line 354 of file IDEA.class.php.
$InputMeasures
IDEA::$InputMeasures protected
Definition at line 379 of file IDEA.class.php.
Referenced by prepareMeasures().
$InputRelations
IDEA::$InputRelations protected
Definition at line 384 of file IDEA.class.php.
Referenced by prepareRelations().
$Max
IDEA::$Max protected
Definition at line 364 of file IDEA.class.php.
$Min
IDEA::$Min protected
Definition at line 359 of file IDEA.class.php.
Referenced by run().
$NbAttributes
IDEA::$NbAttributes protected
Definition at line 369 of file IDEA.class.php.
$NbTuples
IDEA::$NbTuples protected
Definition at line 374 of file IDEA.class.php.
$PreparedMeasures
IDEA::$PreparedMeasures protected
Definition at line 399 of file IDEA.class.php.
$PreparedRelations
IDEA::$PreparedRelations protected
Definition at line 404 of file IDEA.class.php.
$WIPMeasures
IDEA::$WIPMeasures protected
Definition at line 389 of file IDEA.class.php.
$WIPRelations
IDEA::$WIPRelations protected
Definition at line 394 of file IDEA.class.php.
The documentation for this class was generated from the following file:
taged/application/src/algo/IDEA.class.php