TAGED: PageGestAggregate Class Reference
PageGestAggregate Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const GAG_AGGREGATE = 'gag_aggregate'
const GAG_PASSWORD = 'gag_password'
const GAG_SUBMIT = 'gag_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
Protected Attributes
$Password
Detailed Description
Definition at line 8 of file PageGestAggregate.class.php.
Constructor & Destructor Documentation
__construct()
PageGestAggregate::__construct ($InputData = NULL)
Constructeur de la classe PageGestAggregate.
Parameters
mixed $InputData Les données d'entrée pour la page.
Definition at line 30 of file PageGestAggregate.class.php.
References $Data, and handle().
Member Function Documentation
handle()
PageGestAggregate::handle ($Data) protected
Gère le traitement des données d'entrée.
Parameters
mixed $Data Les données d'entrée pour la page.
Definition at line 48 of file PageGestAggregate.class.php.
References $Data, $Password, Analysis\delete(), and show().
Referenced by __construct().
show()
PageGestAggregate::show () protected
Affiche le contenu de la page.
Definition at line 69 of file PageGestAggregate.class.php.
References PageChangeAggregate\CHANGE_AGGREGATE, PageRunAnalysis\RAN_AGGREGATE, and PageShowAggregate\SHOW_AGGREGATE.
Referenced by handle().
Member Data Documentation
$Password
PageGestAggregate::$Password protected
Definition at line 102 of file PageGestAggregate.class.php.
Referenced by handle().
GAG_AGGREGATE
const PageGestAggregate::GAG_AGGREGATE = 'gag_aggregate'
Constante représentant le nom du champ d'agrégation.
Definition at line 13 of file PageGestAggregate.class.php.
GAG_PASSWORD
const PageGestAggregate::GAG_PASSWORD = 'gag_password'
Constante représentant le nom du champ de mot de passe.
Definition at line 18 of file PageGestAggregate.class.php.
GAG_SUBMIT
const PageGestAggregate::GAG_SUBMIT = 'gag_submit'
Constante représentant le nom du champ de soumission du formulaire.
Definition at line 23 of file PageGestAggregate.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageGestAggregate.class.php