TAGED: Match3 Class Reference
Match3 Class Reference
Public Member Functions
__construct ()
__destruct ()
__toString ()
show ()
Protected Member Functions
getGames ()
Protected Attributes
$ListGames
Detailed Description
Definition at line 7 of file Match3.class.php.
Constructor & Destructor Documentation
__construct()
Match3::__construct ()
Definition at line 13 of file Match3.class.php.
References $ListGames, and getGames().
__destruct()
Match3::__destruct ()
Definition at line 21 of file Match3.class.php.
References $ListGames.
Member Function Documentation
__toString()
Match3::__toString ()
Definition at line 30 of file Match3.class.php.
getGames()
Match3::getGames () protected
Definition at line 67 of file Match3.class.php.
References $Result, CollGame\CLASSE, CollGame\ID, CollGame\RESULT, CollGame\RULES, CollGame\TABLE, and CollGame\TIER.
Referenced by __construct().
show()
Match3::show ()
Definition at line 54 of file Match3.class.php.
References CollGame\showTableFooter(), and CollGame\showTableHeader().
Member Data Documentation
$ListGames
Match3::$ListGames protected
Definition at line 9 of file Match3.class.php.
Referenced by __construct(), and __destruct().
The documentation for this class was generated from the following file:
taged/application/src/models/Match3/Match3.class.php