TAGED: M3Game Class Reference
M3Game Class Reference
Public Member Functions
__construct ($IDPlayer='', $PlayerIP='', $GameDate=0, $RoundDate=0, $RoundNum=0, $Strokes=array())
__destruct ()
__toString ()
savePlayer ()
saveGame ()
save ()
Static Public Member Functions
static build ($Array)
static getStats ()
Public Attributes
const TABLE_PLAYER = 'joueur'
const TABLE_GAME = 'partie'
const VIEW_DATA = 'vw_m3_data'
const VIEW_STAT = 'vw_m3_stat'
const ID_PLAYER = 'id_joueur'
const ID_GAME = 'id_partie'
const IP_ADDR = 'ip_addr'
const DATE_GAME = 'date_partie'
const NUM_ROUND = 'num_tour'
const DATE_ROUND = 'date_tour'
const COUNT_PLAYER = 'count_joueur'
const COUNT_GAME = 'count_partie'
const COUNT_STROKE = 'count_coup'
const COUNT_MATCH = 'count_beam'
const WS_PLAYER = 'player'
const WS_PLAYER_ID = 'player_id'
const WS_PLAYER_ADDR = 'ipaddress'
const WS_GAME = 'game'
const WS_GAME_DATE = 'game_date'
const WS_ROUND = 'round'
const WS_ROUND_NUM = 'round_num'
const WS_ROUND_DATE = 'round_date'
const WS_STROKE = 'stroke'
const COUNT_TRAD
Protected Member Functions
addStroke ($StrokeData=array())
fill ()
Protected Attributes
$GameID
$PlayerID
$PlayerIP
$GameDate
$RoundDate
$RoundNum
$Strokes
Private Member Functions
fetchGameId ()
Detailed Description
Definition at line 7 of file M3Game.class.php.
Constructor & Destructor Documentation
__construct()
M3Game::__construct ($IDPlayer = '', $PlayerIP = '', $GameDate = 0, $RoundDate = 0, $RoundNum = 0, $Strokes = array ())
Definition at line 54 of file M3Game.class.php.
References $GameDate, $PlayerIP, $RoundDate, $RoundNum, $Strokes, addStroke(), and fill().
__destruct()
M3Game::__destruct ()
Definition at line 83 of file M3Game.class.php.
Member Function Documentation
__toString()
M3Game::__toString ()
Definition at line 88 of file M3Game.class.php.
addStroke()
M3Game::addStroke ($StrokeData = array ()) protected
Definition at line 128 of file M3Game.class.php.
References M3Stroke\build().
Referenced by __construct().
build()
static M3Game::build ($Array) static
Definition at line 105 of file M3Game.class.php.
References $GameDate, $PlayerID, $PlayerIP, $RoundDate, $RoundNum, and $Strokes.
Referenced by WSMatch3\store().
fetchGameId()
M3Game::fetchGameId () private
Definition at line 158 of file M3Game.class.php.
Referenced by saveGame().
fill()
M3Game::fill () protected
Definition at line 138 of file M3Game.class.php.
Referenced by __construct().
getStats()
static M3Game::getStats () static
Definition at line 176 of file M3Game.class.php.
save()
M3Game::save ()
Definition at line 221 of file M3Game.class.php.
References saveGame(), and savePlayer().
saveGame()
M3Game::saveGame ()
Definition at line 198 of file M3Game.class.php.
References fetchGameId().
Referenced by save().
savePlayer()
M3Game::savePlayer ()
Definition at line 146 of file M3Game.class.php.
Referenced by save().
Member Data Documentation
$GameDate
M3Game::$GameDate protected
Definition at line 47 of file M3Game.class.php.
Referenced by __construct(), and build().
$GameID
M3Game::$GameID protected
Definition at line 44 of file M3Game.class.php.
$PlayerID
M3Game::$PlayerID protected
Definition at line 45 of file M3Game.class.php.
Referenced by build().
$PlayerIP
M3Game::$PlayerIP protected
Definition at line 46 of file M3Game.class.php.
Referenced by __construct(), and build().
$RoundDate
M3Game::$RoundDate protected
Definition at line 48 of file M3Game.class.php.
Referenced by __construct(), and build().
$RoundNum
M3Game::$RoundNum protected
Definition at line 49 of file M3Game.class.php.
Referenced by __construct(), and build().
$Strokes
M3Game::$Strokes protected
Definition at line 50 of file M3Game.class.php.
Referenced by __construct(), and build().
COUNT_GAME
const M3Game::COUNT_GAME = 'count_partie'
Definition at line 23 of file M3Game.class.php.
COUNT_MATCH
const M3Game::COUNT_MATCH = 'count_beam'
Definition at line 25 of file M3Game.class.php.
COUNT_PLAYER
const M3Game::COUNT_PLAYER = 'count_joueur'
Definition at line 22 of file M3Game.class.php.
COUNT_STROKE
const M3Game::COUNT_STROKE = 'count_coup'
Definition at line 24 of file M3Game.class.php.
COUNT_TRAD
const M3Game::COUNT_TRAD
Initial value:
= array (
        self::COUNT_PLAYER => 'Joueurs',
        self::COUNT_GAME   => 'Parties',
        self::COUNT_STROKE => 'Coups',
        self::COUNT_MATCH  => 'Matchs'
    )
Definition at line 37 of file M3Game.class.php.
DATE_GAME
const M3Game::DATE_GAME = 'date_partie'
Definition at line 18 of file M3Game.class.php.
DATE_ROUND
const M3Game::DATE_ROUND = 'date_tour'
Definition at line 20 of file M3Game.class.php.
ID_GAME
const M3Game::ID_GAME = 'id_partie'
Definition at line 16 of file M3Game.class.php.
Referenced by M3Stroke\fetchId(), and M3Stroke\save().
ID_PLAYER
const M3Game::ID_PLAYER = 'id_joueur'
Definition at line 15 of file M3Game.class.php.
IP_ADDR
const M3Game::IP_ADDR = 'ip_addr'
Definition at line 17 of file M3Game.class.php.
NUM_ROUND
const M3Game::NUM_ROUND = 'num_tour'
Definition at line 19 of file M3Game.class.php.
TABLE_GAME
const M3Game::TABLE_GAME = 'partie'
Definition at line 10 of file M3Game.class.php.
TABLE_PLAYER
const M3Game::TABLE_PLAYER = 'joueur'
Definition at line 9 of file M3Game.class.php.
VIEW_DATA
const M3Game::VIEW_DATA = 'vw_m3_data'
Definition at line 12 of file M3Game.class.php.
VIEW_STAT
const M3Game::VIEW_STAT = 'vw_m3_stat'
Definition at line 13 of file M3Game.class.php.
WS_GAME
const M3Game::WS_GAME = 'game'
Definition at line 30 of file M3Game.class.php.
WS_GAME_DATE
const M3Game::WS_GAME_DATE = 'game_date'
Definition at line 31 of file M3Game.class.php.
WS_PLAYER
const M3Game::WS_PLAYER = 'player'
Definition at line 27 of file M3Game.class.php.
WS_PLAYER_ADDR
const M3Game::WS_PLAYER_ADDR = 'ipaddress'
Definition at line 29 of file M3Game.class.php.
WS_PLAYER_ID
const M3Game::WS_PLAYER_ID = 'player_id'
Definition at line 28 of file M3Game.class.php.
WS_ROUND
const M3Game::WS_ROUND = 'round'
Definition at line 32 of file M3Game.class.php.
WS_ROUND_DATE
const M3Game::WS_ROUND_DATE = 'round_date'
Definition at line 34 of file M3Game.class.php.
WS_ROUND_NUM
const M3Game::WS_ROUND_NUM = 'round_num'
Definition at line 33 of file M3Game.class.php.
WS_STROKE
const M3Game::WS_STROKE = 'stroke'
Definition at line 35 of file M3Game.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/Match3/M3Game.class.php