TAGED: WSMatch3 Class Reference
WSMatch3 Class Reference
Public Member Functions
__construct ($InputData=NULL)
serve ()
Public Member Functions inherited from TagedWS
__construct ($InputData=NULL)
Public Attributes
const WS_M3_DATA = 'data'
const WS_M3_SELECTOR = 'm3'
const WS_M3_DEFAULT = 'nothing'
const WS_M3_LIST
Public Attributes inherited from TagedWS
const WS_SELECTOR = 'sel'
const WS_DEFAULT = 'none'
const WS_LIST
Protected Member Functions
store ()
intermediate ()
gameOver ()
newGame ()
getM3Selector ()
Protected Attributes
$InputData
Additional Inherited Members
Static Public Member Functions inherited from TagedWS
static getSelector ()
Detailed Description
Definition at line 9 of file WSMatch3.class.php.
Constructor & Destructor Documentation
__construct()
WSMatch3::__construct ($InputData = NULL)
Constructeur de la classe WSMatch3.
Initialise un nouvel objet WSMatch3 en récupérant les données d'entrée passées en paramètre ou en utilisant la superglobale $_REQUEST si aucun paramètre n'est fourni.
Parameters
array | null $InputData Données d'entrée du service web Match3.
Definition at line 44 of file WSMatch3.class.php.
References $InputData.
Member Function Documentation
gameOver()
WSMatch3::gameOver () protected
Action de fin de partie du Match3.
Appelle la méthode de stockage des données (store) et ne renvoie aucune valeur.
Returns
string Chaîne vide.
Definition at line 109 of file WSMatch3.class.php.
References store().
getM3Selector()
WSMatch3::getM3Selector () protected
Obtient le sélecteur Match3.
Récupère le sélecteur Match3 des données d'entrée et retourne l'action associée dans la liste WS_M3_LIST. Si le sélecteur n'est pas trouvé dans la liste, retourne l'action par défaut WS_M3_DEFAULT.
Returns
string Action associée au sélecteur Match3.
Definition at line 149 of file WSMatch3.class.php.
Referenced by serve().
intermediate()
WSMatch3::intermediate () protected
Action intermédiaire du Match3.
Appelle la méthode de stockage des données (store) et ne renvoie aucune valeur.
Returns
string Chaîne vide.
Definition at line 92 of file WSMatch3.class.php.
References store().
newGame()
WSMatch3::newGame () protected
Action pour démarrer une nouvelle partie du Match3.
Récupère les données du Match3 concernant la nouvelle partie et ne renvoie aucune valeur.
Returns
string Chaîne vide.
Definition at line 126 of file WSMatch3.class.php.
References $Data.
serve()
WSMatch3::serve ()
Fonction principale du service web.
Exécute l'action associée au sélecteur Match3 (récupéré via la méthode getM3Selector) et retourne le résultat.
Returns
string Résultat de l'action du service web Match3.
Definition at line 57 of file WSMatch3.class.php.
References getM3Selector().
store()
WSMatch3::store () protected
Fonction de stockage des données.
Récupère les données du Match3, les traite et les sauvegarde dans la base de données en tant que partie de jeu.
Definition at line 69 of file WSMatch3.class.php.
References $Data, and M3Game\build().
Referenced by gameOver(), and intermediate().
Member Data Documentation
$InputData
WSMatch3::$InputData protected
Definition at line 162 of file WSMatch3.class.php.
Referenced by __construct().
WS_M3_DATA
const WSMatch3::WS_M3_DATA = 'data'
Constante représentant les données Match3.
Definition at line 14 of file WSMatch3.class.php.
WS_M3_DEFAULT
const WSMatch3::WS_M3_DEFAULT = 'nothing'
Constante représentant la valeur par défaut du sélecteur Match3.
Definition at line 24 of file WSMatch3.class.php.
WS_M3_LIST
const WSMatch3::WS_M3_LIST
Initial value:
= array (
        'fin' => 'gameOver',
        'step' => 'intermediate',
        'new' => 'newGame'
    )
Definition at line 30 of file WSMatch3.class.php.
WS_M3_SELECTOR
const WSMatch3::WS_M3_SELECTOR = 'm3'
Constante représentant le sélecteur Match3.
Definition at line 19 of file WSMatch3.class.php.
The documentation for this class was generated from the following file:
taged/application/src/ws/WSMatch3.class.php