TAGED: ReplayParser Class Reference
ReplayParser Class Reference
Public Member Functions
__construct ($name)
matchFunc0 ($match, $callback)
matchFunc1 ($match, $callback)
matchFunc2 ($match, $callback)
matchFunc3 ($match, $callback)
matchFunc4 ($match, $callback)
matchFunc5 ($match, $callback)
matchFunc6 ($match, $callback)
playerPreg ($match)
teamSizePreg ($match)
gameTypePreg ($match)
genPreg ($match)
tierPreg ($match)
ratedPreg ($match)
rulePreg ($match)
teamPreviewPokemonPreg ($match)
turnPreg ($match)
move1Preg ($match)
move2Preg ($match)
winnerPreg ($match)
tiePreg ($match)
move1 ($pokemon, $move, $effect)
move2 ($pokemon, $move, $effect)
player ($player, $username, $avatar, $rating=null)
teamSize ($player, $number)
gameType ($gameType)
gen ($gen)
tier ($tier)
rated ($rated, $message='')
rule ($rule)
teamPreviewPokemon ($player, $details, $item)
turn ($urnNum, $turn)
move ($player, $pokemon, $move, $effect)
effect ()
winner ($user)
tie ($tie=false)
Public Attributes
const REPLAYS_PATH = 'replays/'
Private Member Functions
getPage ()
cleaner ()
parser ()
Private Attributes
$filename
$head
$text
$player1
$player2
$team1
$team2
$gameType
$gen
$rated
$rules
$teamPreview
$currentPokemon1
$currentPokemon2
$turns
$currentTurn
$winner
$tie
Detailed Description
Definition at line 18 of file ReplayParser.class.php.
Constructor & Destructor Documentation
__construct()
ReplayParser::__construct ($name)
Definition at line 40 of file ReplayParser.class.php.
References cleaner(), getPage(), and parser().
Member Function Documentation
cleaner()
ReplayParser::cleaner () private
Definition at line 61 of file ReplayParser.class.php.
References $text.
Referenced by __construct().
effect()
ReplayParser::effect ()
Definition at line 405 of file ReplayParser.class.php.
gameType()
ReplayParser::gameType ($gameType)
Definition at line 338 of file ReplayParser.class.php.
References $gameType.
Referenced by parser().
gameTypePreg()
ReplayParser::gameTypePreg ($match)
Definition at line 256 of file ReplayParser.class.php.
References matchFunc1().
gen()
ReplayParser::gen ($gen)
Definition at line 344 of file ReplayParser.class.php.
References $gen.
Referenced by parser().
genPreg()
ReplayParser::genPreg ($match)
Definition at line 260 of file ReplayParser.class.php.
References matchFunc1().
getPage()
ReplayParser::getPage () private
Definition at line 53 of file ReplayParser.class.php.
Referenced by __construct().
matchFunc0()
ReplayParser::matchFunc0 ($match, $callback)
Definition at line 156 of file ReplayParser.class.php.
Referenced by tiePreg().
matchFunc1()
ReplayParser::matchFunc1 ($match, $callback)
Definition at line 162 of file ReplayParser.class.php.
Referenced by gameTypePreg(), genPreg(), rulePreg(), tierPreg(), and winnerPreg().
matchFunc2()
ReplayParser::matchFunc2 ($match, $callback)
Definition at line 168 of file ReplayParser.class.php.
Referenced by ratedPreg(), teamSizePreg(), and turnPreg().
matchFunc3()
ReplayParser::matchFunc3 ($match, $callback)
Definition at line 178 of file ReplayParser.class.php.
Referenced by move1Preg(), move2Preg(), and teamPreviewPokemonPreg().
matchFunc4()
ReplayParser::matchFunc4 ($match, $callback)
Definition at line 190 of file ReplayParser.class.php.
Referenced by playerPreg().
matchFunc5()
ReplayParser::matchFunc5 ($match, $callback)
Definition at line 205 of file ReplayParser.class.php.
matchFunc6()
ReplayParser::matchFunc6 ($match, $callback)
Definition at line 223 of file ReplayParser.class.php.
move()
ReplayParser::move ($player, $pokemon, $move, $effect)
Definition at line 391 of file ReplayParser.class.php.
Referenced by move1(), and move2().
move1()
ReplayParser::move1 ($pokemon, $move, $effect)
Definition at line 304 of file ReplayParser.class.php.
References move().
move1Preg()
ReplayParser::move1Preg ($match)
Definition at line 284 of file ReplayParser.class.php.
References matchFunc3().
move2()
ReplayParser::move2 ($pokemon, $move, $effect)
Definition at line 308 of file ReplayParser.class.php.
References move().
move2Preg()
ReplayParser::move2Preg ($match)
Definition at line 288 of file ReplayParser.class.php.
References matchFunc3().
parser()
ReplayParser::parser () private
Definition at line 67 of file ReplayParser.class.php.
References $text, gameType(), gen(), rated(), tie(), tier(), and winner().
Referenced by __construct().
player()
ReplayParser::player ($player, $username, $avatar, $rating = null)
Definition at line 316 of file ReplayParser.class.php.
playerPreg()
ReplayParser::playerPreg ($match)
Definition at line 248 of file ReplayParser.class.php.
References matchFunc4().
rated()
ReplayParser::rated ($rated, $message = '')
Definition at line 356 of file ReplayParser.class.php.
References $rated.
Referenced by parser().
ratedPreg()
ReplayParser::ratedPreg ($match)
Definition at line 268 of file ReplayParser.class.php.
References matchFunc2().
rule()
ReplayParser::rule ($rule)
Definition at line 365 of file ReplayParser.class.php.
rulePreg()
ReplayParser::rulePreg ($match)
Definition at line 272 of file ReplayParser.class.php.
References matchFunc1().
teamPreviewPokemon()
ReplayParser::teamPreviewPokemon ($player, $details, $item)
Definition at line 371 of file ReplayParser.class.php.
teamPreviewPokemonPreg()
ReplayParser::teamPreviewPokemonPreg ($match)
Definition at line 276 of file ReplayParser.class.php.
References matchFunc3().
teamSize()
ReplayParser::teamSize ($player, $number)
Definition at line 328 of file ReplayParser.class.php.
teamSizePreg()
ReplayParser::teamSizePreg ($match)
Definition at line 252 of file ReplayParser.class.php.
References matchFunc2().
tie()
ReplayParser::tie ($tie = false)
Definition at line 432 of file ReplayParser.class.php.
References $tie.
Referenced by parser().
tiePreg()
ReplayParser::tiePreg ($match)
Definition at line 296 of file ReplayParser.class.php.
References matchFunc0().
tier()
ReplayParser::tier ($tier)
Definition at line 350 of file ReplayParser.class.php.
Referenced by parser().
tierPreg()
ReplayParser::tierPreg ($match)
Definition at line 264 of file ReplayParser.class.php.
References matchFunc1().
turn()
ReplayParser::turn ($urnNum, $turn)
Definition at line 377 of file ReplayParser.class.php.
turnPreg()
ReplayParser::turnPreg ($match)
Definition at line 280 of file ReplayParser.class.php.
References matchFunc2().
winner()
ReplayParser::winner ($user)
Definition at line 426 of file ReplayParser.class.php.
Referenced by parser().
winnerPreg()
ReplayParser::winnerPreg ($match)
Definition at line 292 of file ReplayParser.class.php.
References matchFunc1().
Member Data Documentation
$currentPokemon1
ReplayParser::$currentPokemon1 private
Definition at line 33 of file ReplayParser.class.php.
$currentPokemon2
ReplayParser::$currentPokemon2 private
Definition at line 34 of file ReplayParser.class.php.
$currentTurn
ReplayParser::$currentTurn private
Definition at line 36 of file ReplayParser.class.php.
$filename
ReplayParser::$filename private
Definition at line 21 of file ReplayParser.class.php.
$gameType
ReplayParser::$gameType private
Definition at line 28 of file ReplayParser.class.php.
Referenced by gameType().
$gen
ReplayParser::$gen private
Definition at line 29 of file ReplayParser.class.php.
Referenced by gen().
$head
ReplayParser::$head private
Definition at line 22 of file ReplayParser.class.php.
$player1
ReplayParser::$player1 private
Definition at line 24 of file ReplayParser.class.php.
$player2
ReplayParser::$player2 private
Definition at line 25 of file ReplayParser.class.php.
$rated
ReplayParser::$rated private
Definition at line 30 of file ReplayParser.class.php.
Referenced by rated().
$rules
ReplayParser::$rules private
Definition at line 31 of file ReplayParser.class.php.
$team1
ReplayParser::$team1 private
Definition at line 26 of file ReplayParser.class.php.
$team2
ReplayParser::$team2 private
Definition at line 27 of file ReplayParser.class.php.
$teamPreview
ReplayParser::$teamPreview private
Definition at line 32 of file ReplayParser.class.php.
$text
ReplayParser::$text private
Definition at line 23 of file ReplayParser.class.php.
Referenced by cleaner(), and parser().
$tie
ReplayParser::$tie private
Definition at line 38 of file ReplayParser.class.php.
Referenced by tie().
$turns
ReplayParser::$turns private
Definition at line 35 of file ReplayParser.class.php.
$winner
ReplayParser::$winner private
Definition at line 37 of file ReplayParser.class.php.
REPLAYS_PATH
const ReplayParser::REPLAYS_PATH = 'replays/'
Definition at line 19 of file ReplayParser.class.php.
The documentation for this class was generated from the following file:
taged/application/old/ReplayParser.class.php