TAGED: DisplaySkyCube Class Reference
DisplaySkyCube Class Reference
Public Member Functions
__construct ($Data, $RelationCols, $MeasureCols, $MinMax=Cuboide::TO_MAX)
toLaTex ()
__toString ()
getDataSet ()
getRowHeaders ()
getColIDs ()
Public Attributes
const MAX_CUBOIDE = 128
const MIN_COLID = 'A'
const CUBOIDE = 'Cuboide'
Protected Member Functions
generateCuboideListLvl ($Level, $ColIDs, $Current='')
generateCuboideList ()
computeDataSet ($Data, $RelationCols, $MeasureCols)
Protected Attributes
$DataSet
$RowHeaders
$ColIDs
$Cuboides
$MinMax
$IsValid
Detailed Description
Definition at line 7 of file DisplaySkyCube.class.php.
Constructor & Destructor Documentation
__construct()
DisplaySkyCube::__construct ($Data, $RelationCols, $MeasureCols, $MinMax = Cuboide::TO_MAX)
Definition at line 14 of file DisplaySkyCube.class.php.
References $Data, $MinMax, computeDataSet(), and generateCuboideList().
Member Function Documentation
__toString()
DisplaySkyCube::__toString ()
Definition at line 120 of file DisplaySkyCube.class.php.
References $Cuboides.
computeDataSet()
DisplaySkyCube::computeDataSet ($Data, $RelationCols, $MeasureCols) protected
Definition at line 205 of file DisplaySkyCube.class.php.
References $Data.
Referenced by __construct().
generateCuboideList()
DisplaySkyCube::generateCuboideList () protected
Definition at line 182 of file DisplaySkyCube.class.php.
References generateCuboideListLvl().
Referenced by __construct().
generateCuboideListLvl()
DisplaySkyCube::generateCuboideListLvl ($Level, $ColIDs, $Current = '') protected
Definition at line 154 of file DisplaySkyCube.class.php.
References $ColIDs.
Referenced by generateCuboideList().
getColIDs()
DisplaySkyCube::getColIDs ()
Definition at line 273 of file DisplaySkyCube.class.php.
References $ColIDs.
getDataSet()
DisplaySkyCube::getDataSet ()
Definition at line 263 of file DisplaySkyCube.class.php.
References $DataSet.
getRowHeaders()
DisplaySkyCube::getRowHeaders ()
Definition at line 268 of file DisplaySkyCube.class.php.
References $RowHeaders.
toLaTex()
DisplaySkyCube::toLaTex ()
Definition at line 49 of file DisplaySkyCube.class.php.
References $Cuboides.
Member Data Documentation
$ColIDs
DisplaySkyCube::$ColIDs protected
Definition at line 280 of file DisplaySkyCube.class.php.
Referenced by generateCuboideListLvl(), and getColIDs().
$Cuboides
DisplaySkyCube::$Cuboides protected
Definition at line 281 of file DisplaySkyCube.class.php.
Referenced by __toString(), and toLaTex().
$DataSet
DisplaySkyCube::$DataSet protected
Definition at line 278 of file DisplaySkyCube.class.php.
Referenced by getDataSet().
$IsValid
DisplaySkyCube::$IsValid protected
Definition at line 283 of file DisplaySkyCube.class.php.
$MinMax
DisplaySkyCube::$MinMax protected
Definition at line 282 of file DisplaySkyCube.class.php.
Referenced by __construct().
$RowHeaders
DisplaySkyCube::$RowHeaders protected
Definition at line 279 of file DisplaySkyCube.class.php.
Referenced by getRowHeaders().
CUBOIDE
const DisplaySkyCube::CUBOIDE = 'Cuboide'
Definition at line 12 of file DisplaySkyCube.class.php.
MAX_CUBOIDE
const DisplaySkyCube::MAX_CUBOIDE = 128
Definition at line 9 of file DisplaySkyCube.class.php.
MIN_COLID
const DisplaySkyCube::MIN_COLID = 'A'
Definition at line 10 of file DisplaySkyCube.class.php.
The documentation for this class was generated from the following file:
taged/application/old/DisplaySkyCube.class.php