TAGED: PageAccueil Class Reference
PageAccueil Class Reference
Public Member Functions
__construct ($InputData=NULL)
addStats ()
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Protected Member Functions
computeStats ($App)
computeStatsDB ($App)
computeStatsFiles ($App)
computeAllStats ()
doStatHead ($Columns)
doStatLine ($Stats, $Columns, $Part='main')
doStats ($Data)
addStat ($Data, $StatType)
Protected Attributes
$Cols
Additional Inherited Members
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Detailed Description
Definition at line 8 of file PageAccueil.class.php.
Constructor & Destructor Documentation
__construct()
PageAccueil::__construct ($InputData = NULL)
Constructeur de la classe PageAccueil.
Parameters
mixed $InputData Les données d'entrée pour la page.
Definition at line 15 of file PageAccueil.class.php.
References $Data, and addStats().
Member Function Documentation
addStat()
PageAccueil::addStat ($Data, $StatType) protected
Ajoute une section de statistiques au contenu de la page.
Parameters
array $Data Les données de statistiques.
string $StatType Le type de statistiques.
Returns
string La section de statistiques au format HTML.
Definition at line 258 of file PageAccueil.class.php.
References $Data, and doStats().
Referenced by addStats().
addStats()
PageAccueil::addStats ()
Ajoute toutes les statistiques calculées à la page.
Definition at line 268 of file PageAccueil.class.php.
References $Data, addStat(), and computeAllStats().
Referenced by __construct().
computeAllStats()
PageAccueil::computeAllStats () protected
Calcule toutes les statistiques pour toutes les applications.
Returns
array Les statistiques calculées pour toutes les applications.
Definition at line 167 of file PageAccueil.class.php.
References $GLOBALS, APP_LIST, APP_NAME, and computeStats().
Referenced by addStats().
computeStats()
PageAccueil::computeStats ($App) protected
Calcule les statistiques pour l'application spécifiée.
Parameters
array $App Les données de l'application.
Returns
array Les statistiques calculées.
Definition at line 33 of file PageAccueil.class.php.
References computeStatsDB(), computeStatsFiles(), STATS_DB, and STATS_FILE.
Referenced by computeAllStats().
computeStatsDB()
PageAccueil::computeStatsDB ($App) protected
Calcule les statistiques à partir de la base de données pour l'application spécifiée.
Parameters
array $App Les données de l'application.
Returns
array Les statistiques calculées depuis la base de données.
Definition at line 53 of file PageAccueil.class.php.
References $Data, STATS_COLS, STATS_DATA, and STATS_DB.
Referenced by computeStats().
computeStatsFiles()
PageAccueil::computeStatsFiles ($App) protected
Calcule les statistiques à partir des fichiers pour l'application spécifiée.
Parameters
array $App Les données de l'application.
Returns
array Les statistiques calculées depuis les fichiers.
Definition at line 90 of file PageAccueil.class.php.
References $Data, APP_NAME, DATA_HOME, STATS_COLS, STATS_DATA, and STATS_SEPARATOR.
Referenced by computeStats().
doStatHead()
PageAccueil::doStatHead ($Columns) protected
Génère la ligne d'en-tête du tableau de statistiques.
Parameters
array $Columns Les colonnes du tableau.
Returns
string La ligne d'en-tête du tableau de statistiques.
Definition at line 185 of file PageAccueil.class.php.
Referenced by doStats().
doStatLine()
PageAccueil::doStatLine ($Stats, $Columns, $Part = 'main') protected
Génère une ligne de statistiques pour le tableau.
Parameters
array $Stats Les statistiques.
array $Columns Les colonnes du tableau.
string $Part La partie des statistiques.
Returns
string La ligne de statistiques pour le tableau.
Definition at line 203 of file PageAccueil.class.php.
Referenced by doStats().
doStats()
PageAccueil::doStats ($Data) protected
Génère le tableau de statistiques.
Parameters
array $Data Les données de statistiques.
Returns
string Le tableau de statistiques au format HTML.
Definition at line 219 of file PageAccueil.class.php.
References $Data, doStatHead(), doStatLine(), STATS_COLS, and STATS_DATA.
Referenced by addStat().
Member Data Documentation
$Cols
PageAccueil::$Cols protected
Definition at line 295 of file PageAccueil.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageAccueil.class.php