TAGED: HnsItem Class Reference
HnsItem Class Reference
Public Member Functions
__construct ($Position='', $Image='', $Name='', $Affix=array())
Hero constructor.
__toString ()
setPosition ($NewValue)
setImage ($NewValue)
setName ($NewValue)
setAffix ($NewValue)
addAffix ($NewValue)
getPosition ()
getImage ()
getName ()
getAffix ()
getId ()
save ($HeroId)
Public Attributes
const TABLE = 'equip'
const ID = 'id_equip'
const NOM = 'nomequip'
const PLACE = 'place'
const TABLE_PORTE = 'porte'
const ID_PORTE = 'id_porte'
const COTE = 'cote'
const COTE_LEFT = 'Left'
const COTE_RIGHT = 'Right'
Private Member Functions
fetchId ()
porte ($HeroId)
Private Attributes
$Id
$IdPorte
$Position
$Image
$Name
$Affix
$Place
$Cote
Detailed Description
Definition at line 7 of file HnSItem.class.php.
Constructor & Destructor Documentation
__construct()
HnsItem::__construct ($Position = '', $Image = '', $Name = '', $Affix = array ())
Hero constructor.
Parameters
int $Hero The position of the player
string $Username The name of the user playing
int $Avatar The avatar of the user
int $Rating The rating of the user
Definition at line 36 of file HnSItem.class.php.
References $Affix, $Image, $Name, $Position, setName(), and setPosition().
Member Function Documentation
__toString()
HnsItem::__toString ()
Definition at line 44 of file HnSItem.class.php.
References $Affix, $Cote, and $Result.
addAffix()
HnsItem::addAffix ($NewValue)
Definition at line 80 of file HnSItem.class.php.
fetchId()
HnsItem::fetchId () private
Definition at line 93 of file HnSItem.class.php.
Referenced by getId(), and save().
getAffix()
HnsItem::getAffix ()
Definition at line 85 of file HnSItem.class.php.
References $Affix.
getId()
HnsItem::getId ()
Definition at line 87 of file HnSItem.class.php.
References $Id, and fetchId().
getImage()
HnsItem::getImage ()
Definition at line 83 of file HnSItem.class.php.
References $Image.
getName()
HnsItem::getName ()
Definition at line 84 of file HnSItem.class.php.
References $Name.
getPosition()
HnsItem::getPosition ()
Definition at line 82 of file HnSItem.class.php.
References $Position.
porte()
HnsItem::porte ($HeroId) private
Definition at line 106 of file HnSItem.class.php.
References Hero\ID.
Referenced by save().
save()
HnsItem::save ($HeroId)
Definition at line 122 of file HnSItem.class.php.
References fetchId(), and porte().
setAffix()
HnsItem::setAffix ($NewValue)
Definition at line 79 of file HnSItem.class.php.
setImage()
HnsItem::setImage ($NewValue)
Definition at line 77 of file HnSItem.class.php.
setName()
HnsItem::setName ($NewValue)
Definition at line 78 of file HnSItem.class.php.
Referenced by __construct().
setPosition()
HnsItem::setPosition ($NewValue)
Definition at line 58 of file HnSItem.class.php.
Referenced by __construct().
Member Data Documentation
$Affix
HnsItem::$Affix private
Definition at line 25 of file HnSItem.class.php.
Referenced by __construct(), __toString(), and getAffix().
$Cote
HnsItem::$Cote private
Definition at line 27 of file HnSItem.class.php.
Referenced by __toString().
$Id
HnsItem::$Id private
Definition at line 20 of file HnSItem.class.php.
Referenced by getId().
$IdPorte
HnsItem::$IdPorte private
Definition at line 21 of file HnSItem.class.php.
$Image
HnsItem::$Image private
Definition at line 23 of file HnSItem.class.php.
Referenced by __construct(), and getImage().
$Name
HnsItem::$Name private
Definition at line 24 of file HnSItem.class.php.
Referenced by __construct(), and getName().
$Place
HnsItem::$Place private
Definition at line 26 of file HnSItem.class.php.
$Position
HnsItem::$Position private
Definition at line 22 of file HnSItem.class.php.
Referenced by __construct(), and getPosition().
COTE
const HnsItem::COTE = 'cote'
Definition at line 16 of file HnSItem.class.php.
COTE_LEFT
const HnsItem::COTE_LEFT = 'Left'
Definition at line 17 of file HnSItem.class.php.
COTE_RIGHT
const HnsItem::COTE_RIGHT = 'Right'
Definition at line 18 of file HnSItem.class.php.
ID
const HnsItem::ID = 'id_equip'
Definition at line 10 of file HnSItem.class.php.
ID_PORTE
const HnsItem::ID_PORTE = 'id_porte'
Definition at line 15 of file HnSItem.class.php.
NOM
const HnsItem::NOM = 'nomequip'
Definition at line 11 of file HnSItem.class.php.
PLACE
const HnsItem::PLACE = 'place'
Definition at line 12 of file HnSItem.class.php.
TABLE
const HnsItem::TABLE = 'equip'
Definition at line 9 of file HnSItem.class.php.
TABLE_PORTE
const HnsItem::TABLE_PORTE = 'porte'
Definition at line 14 of file HnSItem.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/HnS/HnSItem.class.php