TAGED: PageRunAnalysis Class Reference
PageRunAnalysis Class Reference
Public Member Functions
__construct ($InputData=NULL)
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const RAN_AGGREGATE = 'ran_aggregate'
const RAN_PASSWORD = 'ran_password'
const RAN_ALGO = 'ran_algo'
const RAN_SUBMIT = 'ran_submit'
const SHOW_TEST = 'ran_test'
const RAN_MIN = 'ran_min'
const RAN_MAX = 'ran_max'
const SHOW_INPUT = 'ran_input'
const SHOW_ESPACE = 'ran_espace'
const SHOW_ACCORDS = 'ran_accords'
const SHOW_DATACUBE = 'ran_skycube'
const SHOW_SKYCUBE = 'ran_sc_red'
const SHOW_FUSION = 'ran_fusion'
const SHOW_FUS_ABREGE = 'ran_fus_abr'
const SHOW_COSKY = 'ran_cosky'
const SHOW_TAGED_CUBE = 'ran_sc_tag'
const RAN_MIN1 = 'ran_min1'
const RAN_MIN2 = 'ran_min2'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
handle ($Data)
show ()
Protected Attributes
$Password
$Aggregate
$AggregateObj
$AggregateListObj
$AggregateList
$Test
$Min
$Max
$CoSky1
$CoSky2
$ShowInput
$ShowEspace
$ShowAccords
$ShowDataCube
$ShowSkyCube
$ShowFusion
$ShowFusionAbregee
$ShowCoSky
$ShowTagedCube
Detailed Description
Definition at line 8 of file PageRunAnalysis.class.php.
Constructor & Destructor Documentation
__construct() [1/2]
PageRunAnalysis::__construct ($InputData = NULL)
Constructeur de la classe PageRunAnalysis.
Parameters
mixed $InputData Données d'entrée pour la page.
Definition at line 110 of file PageRunAnalysis.class.php.
References $Data, Algo\generateList(), and handle().
__construct() [2/2]
PageRunAnalysis::__construct ($InputData = NULL)
Definition at line 16 of file PageRunAnalysis_old.class.php.
References $Data, Algo\generateList(), and handle().
Member Function Documentation
handle() [1/2]
PageRunAnalysis::handle ($Data) protected
Definition at line 36 of file PageRunAnalysis_old.class.php.
References $Data, $Password, $Result, ANALYSIS_PARAM_M, ANALYSIS_PARAM_N, and show().
handle() [2/2]
PageRunAnalysis::handle ($Data) protected
Gère les données d'entrée et le lancement de l'analyse.
Parameters
array $Data Données d'entrée.
Definition at line 134 of file PageRunAnalysis.class.php.
References $Data, $Password, CoSky\run(), and show().
Referenced by __construct().
show() [1/2]
PageRunAnalysis::show () protected
Definition at line 73 of file PageRunAnalysis_old.class.php.
References $Aggregate, $AggregateList, $AggregateListObj, $AggregateObj, $Algo, and $Password.
show() [2/2]
PageRunAnalysis::show () protected
Affiche le contenu de la page.
Definition at line 194 of file PageRunAnalysis.class.php.
References $Aggregate, $Algo, $Max, $Min, $Password, $Result, SKDisplay\htmlCoSky(), SKDisplay\htmlEmergence(), SKDisplay\htmlInputData(), SKDisplay\htmlMultidimensionalSpace(), SKDisplay\htmlSkyCubeFusion(), SKDisplay\htmlSkyCubeParam(), SKDisplay\SHOW_DATA_FILTERED, SKDisplay\SHOW_DATA_RAW, SKDisplay\SHOW_EQUIV_CLASS, SKDisplay\SHOW_EQUIV_CLASS_FILTERED, SKDisplay\SHOW_FILTERED, and SKDisplay\SHOW_REMOVED.
Referenced by handle().
Member Data Documentation
$Aggregate
PageRunAnalysis::$Aggregate protected
Definition at line 349 of file PageRunAnalysis.class.php.
Referenced by show().
$AggregateList
PageRunAnalysis::$AggregateList protected
Definition at line 370 of file PageRunAnalysis.class.php.
Referenced by show().
$AggregateListObj
PageRunAnalysis::$AggregateListObj protected
Definition at line 363 of file PageRunAnalysis.class.php.
Referenced by show().
$AggregateObj
PageRunAnalysis::$AggregateObj protected
Definition at line 356 of file PageRunAnalysis.class.php.
Referenced by show().
$CoSky1
PageRunAnalysis::$CoSky1 protected
Definition at line 398 of file PageRunAnalysis.class.php.
$CoSky2
PageRunAnalysis::$CoSky2 protected
Definition at line 405 of file PageRunAnalysis.class.php.
$Max
PageRunAnalysis::$Max protected
Definition at line 391 of file PageRunAnalysis.class.php.
Referenced by show().
$Min
PageRunAnalysis::$Min protected
Definition at line 384 of file PageRunAnalysis.class.php.
Referenced by show().
$Password
PageRunAnalysis::$Password protected
Definition at line 342 of file PageRunAnalysis.class.php.
Referenced by handle(), and show().
$ShowAccords
PageRunAnalysis::$ShowAccords protected
Definition at line 426 of file PageRunAnalysis.class.php.
$ShowCoSky
PageRunAnalysis::$ShowCoSky protected
Definition at line 461 of file PageRunAnalysis.class.php.
$ShowDataCube
PageRunAnalysis::$ShowDataCube protected
Definition at line 433 of file PageRunAnalysis.class.php.
$ShowEspace
PageRunAnalysis::$ShowEspace protected
Definition at line 419 of file PageRunAnalysis.class.php.
$ShowFusion
PageRunAnalysis::$ShowFusion protected
Definition at line 447 of file PageRunAnalysis.class.php.
$ShowFusionAbregee
PageRunAnalysis::$ShowFusionAbregee protected
Definition at line 454 of file PageRunAnalysis.class.php.
$ShowInput
PageRunAnalysis::$ShowInput protected
Definition at line 412 of file PageRunAnalysis.class.php.
$ShowSkyCube
PageRunAnalysis::$ShowSkyCube protected
Definition at line 440 of file PageRunAnalysis.class.php.
$ShowTagedCube
PageRunAnalysis::$ShowTagedCube protected
Definition at line 468 of file PageRunAnalysis.class.php.
$Test
PageRunAnalysis::$Test protected
Definition at line 377 of file PageRunAnalysis.class.php.
RAN_AGGREGATE
const PageRunAnalysis::RAN_AGGREGATE = 'ran_aggregate'
Definition at line 14 of file PageRunAnalysis.class.php.
Referenced by PageGestAggregate\show().
RAN_ALGO
const PageRunAnalysis::RAN_ALGO = 'ran_algo'
Definition at line 26 of file PageRunAnalysis.class.php.
RAN_MAX
const PageRunAnalysis::RAN_MAX = 'ran_max'
Definition at line 50 of file PageRunAnalysis.class.php.
RAN_MIN
const PageRunAnalysis::RAN_MIN = 'ran_min'
Definition at line 44 of file PageRunAnalysis.class.php.
RAN_MIN1
const PageRunAnalysis::RAN_MIN1 = 'ran_min1'
Definition at line 12 of file PageRunAnalysis_old.class.php.
RAN_MIN2
const PageRunAnalysis::RAN_MIN2 = 'ran_min2'
Definition at line 13 of file PageRunAnalysis_old.class.php.
RAN_PASSWORD
const PageRunAnalysis::RAN_PASSWORD = 'ran_password'
Definition at line 20 of file PageRunAnalysis.class.php.
RAN_SUBMIT
const PageRunAnalysis::RAN_SUBMIT = 'ran_submit'
Definition at line 32 of file PageRunAnalysis.class.php.
SHOW_ACCORDS
const PageRunAnalysis::SHOW_ACCORDS = 'ran_accords'
Definition at line 68 of file PageRunAnalysis.class.php.
SHOW_COSKY
const PageRunAnalysis::SHOW_COSKY = 'ran_cosky'
Definition at line 98 of file PageRunAnalysis.class.php.
SHOW_DATACUBE
const PageRunAnalysis::SHOW_DATACUBE = 'ran_skycube'
Definition at line 74 of file PageRunAnalysis.class.php.
SHOW_ESPACE
const PageRunAnalysis::SHOW_ESPACE = 'ran_espace'
Definition at line 62 of file PageRunAnalysis.class.php.
SHOW_FUS_ABREGE
const PageRunAnalysis::SHOW_FUS_ABREGE = 'ran_fus_abr'
Definition at line 92 of file PageRunAnalysis.class.php.
SHOW_FUSION
const PageRunAnalysis::SHOW_FUSION = 'ran_fusion'
Definition at line 86 of file PageRunAnalysis.class.php.
SHOW_INPUT
const PageRunAnalysis::SHOW_INPUT = 'ran_input'
Definition at line 56 of file PageRunAnalysis.class.php.
SHOW_SKYCUBE
const PageRunAnalysis::SHOW_SKYCUBE = 'ran_sc_red'
Definition at line 80 of file PageRunAnalysis.class.php.
SHOW_TAGED_CUBE
const PageRunAnalysis::SHOW_TAGED_CUBE = 'ran_sc_tag'
Definition at line 104 of file PageRunAnalysis.class.php.
SHOW_TEST
const PageRunAnalysis::SHOW_TEST = 'ran_test'
Definition at line 38 of file PageRunAnalysis.class.php.
The documentation for this class was generated from the following files:
taged/application/src/pages/PageRunAnalysis.class.php
taged/application/src/pages/PageRunAnalysis_old.class.php