TAGED: DisplayCuboide Class Reference
DisplayCuboide Class Reference
Public Member Functions
__construct ($CuboideID, $SkyCube, $MinMax=self::TO_MAX)
__toString ()
toHTML ()
toLaTeX ($Node, $X, $Y)
Public Attributes
const TO_MAX = 'max'
const TO_MIN = 'min'
const TEST_ON = self::TO_MAX
Protected Member Functions
computeDataSet ($SkyCube)
computeCuboide ()
getLaTeXHeader ($ColHeader)
isInCuboide ($ConsideredRowID)
Protected Attributes
$ID
$DataSet
$RowHeaders
$ColIDs
$MinMax
$IsValid
$MaxCols
Detailed Description
Definition at line 6 of file DisplayCuboide.class.php.
Constructor & Destructor Documentation
__construct()
DisplayCuboide::__construct ($CuboideID, $SkyCube, $MinMax = self::TO_MAX)
Definition at line 13 of file DisplayCuboide.class.php.
References $MinMax, computeCuboide(), and computeDataSet().
Member Function Documentation
__toString()
DisplayCuboide::__toString ()
Definition at line 41 of file DisplayCuboide.class.php.
computeCuboide()
DisplayCuboide::computeCuboide () protected
Definition at line 130 of file DisplayCuboide.class.php.
References isInCuboide().
Referenced by __construct().
computeDataSet()
DisplayCuboide::computeDataSet ($SkyCube) protected
Definition at line 88 of file DisplayCuboide.class.php.
Referenced by __construct().
getLaTeXHeader()
DisplayCuboide::getLaTeXHeader ($ColHeader) protected
Definition at line 150 of file DisplayCuboide.class.php.
isInCuboide()
DisplayCuboide::isInCuboide ($ConsideredRowID) protected
Definition at line 207 of file DisplayCuboide.class.php.
Referenced by computeCuboide().
toHTML()
DisplayCuboide::toHTML ()
Definition at line 49 of file DisplayCuboide.class.php.
toLaTeX()
DisplayCuboide::toLaTeX ($Node, $X, $Y)
Definition at line 157 of file DisplayCuboide.class.php.
References $ID, and $Result.
Member Data Documentation
$ColIDs
DisplayCuboide::$ColIDs protected
Definition at line 215 of file DisplayCuboide.class.php.
$DataSet
DisplayCuboide::$DataSet protected
Definition at line 213 of file DisplayCuboide.class.php.
$ID
DisplayCuboide::$ID protected
Definition at line 212 of file DisplayCuboide.class.php.
Referenced by toLaTeX().
$IsValid
DisplayCuboide::$IsValid protected
Definition at line 217 of file DisplayCuboide.class.php.
$MaxCols
DisplayCuboide::$MaxCols protected
Definition at line 218 of file DisplayCuboide.class.php.
$MinMax
DisplayCuboide::$MinMax protected
Definition at line 216 of file DisplayCuboide.class.php.
Referenced by __construct().
$RowHeaders
DisplayCuboide::$RowHeaders protected
Definition at line 214 of file DisplayCuboide.class.php.
TEST_ON
const DisplayCuboide::TEST_ON = self::TO_MAX
Definition at line 11 of file DisplayCuboide.class.php.
TO_MAX
const DisplayCuboide::TO_MAX = 'max'
Definition at line 8 of file DisplayCuboide.class.php.
TO_MIN
const DisplayCuboide::TO_MIN = 'min'
Definition at line 9 of file DisplayCuboide.class.php.
The documentation for this class was generated from the following file:
taged/application/old/DisplayCuboide.class.php