TAGED: PageRunSkyCubeAnalysis Class Reference
PageRunSkyCubeAnalysis Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const RAN_AGGREGATE = 'ran_aggregate'
const RAN_PASSWORD = 'ran_password'
const RAN_ALGO = 'ran_algo'
const RAN_MIN1 = 'ran_min1'
const RAN_MIN2 = 'ran_min2'
const RAN_SUBMIT = 'ran_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
Protected Attributes
$Password
$Aggregate
$AggregateObj
$AggregateListObj
$AggregateList
Detailed Description
Definition at line 7 of file PageRunSkyCubeAnalysis.class.php.
Constructor & Destructor Documentation
__construct()
PageRunSkyCubeAnalysis::__construct ($InputData = NULL)
Definition at line 16 of file PageRunSkyCubeAnalysis.class.php.
References $Data, Algo\generateList(), and handle().
Member Function Documentation
handle()
PageRunSkyCubeAnalysis::handle ($Data) protected
Definition at line 36 of file PageRunSkyCubeAnalysis.class.php.
References $Data, $Password, $Result, show(), and Cuboide\TO_MIN.
Referenced by __construct().
show()
PageRunSkyCubeAnalysis::show () protected
Definition at line 73 of file PageRunSkyCubeAnalysis.class.php.
References $Aggregate, $Algo, $Password, ANALYSIS_PARAM_M, and ANALYSIS_PARAM_N.
Referenced by handle().
Member Data Documentation
$Aggregate
PageRunSkyCubeAnalysis::$Aggregate protected
Definition at line 123 of file PageRunSkyCubeAnalysis.class.php.
Referenced by show().
$AggregateList
PageRunSkyCubeAnalysis::$AggregateList protected
Definition at line 127 of file PageRunSkyCubeAnalysis.class.php.
$AggregateListObj
PageRunSkyCubeAnalysis::$AggregateListObj protected
Definition at line 126 of file PageRunSkyCubeAnalysis.class.php.
$AggregateObj
PageRunSkyCubeAnalysis::$AggregateObj protected
Definition at line 124 of file PageRunSkyCubeAnalysis.class.php.
$Password
PageRunSkyCubeAnalysis::$Password protected
Definition at line 122 of file PageRunSkyCubeAnalysis.class.php.
Referenced by handle(), and show().
RAN_AGGREGATE
const PageRunSkyCubeAnalysis::RAN_AGGREGATE = 'ran_aggregate'
Definition at line 9 of file PageRunSkyCubeAnalysis.class.php.
RAN_ALGO
const PageRunSkyCubeAnalysis::RAN_ALGO = 'ran_algo'
Definition at line 11 of file PageRunSkyCubeAnalysis.class.php.
RAN_MIN1
const PageRunSkyCubeAnalysis::RAN_MIN1 = 'ran_min1'
Definition at line 12 of file PageRunSkyCubeAnalysis.class.php.
RAN_MIN2
const PageRunSkyCubeAnalysis::RAN_MIN2 = 'ran_min2'
Definition at line 13 of file PageRunSkyCubeAnalysis.class.php.
RAN_PASSWORD
const PageRunSkyCubeAnalysis::RAN_PASSWORD = 'ran_password'
Definition at line 10 of file PageRunSkyCubeAnalysis.class.php.
RAN_SUBMIT
const PageRunSkyCubeAnalysis::RAN_SUBMIT = 'ran_submit'
Definition at line 14 of file PageRunSkyCubeAnalysis.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageRunSkyCubeAnalysis.class.php