TAGED: HnsComp Class Reference
HnsComp Class Reference
Public Member Functions
__construct ($Skill='', $Order='', $Type=self::TYPE_PASSIVE, $Rune='')
Hero constructor.
__toString ()
setSkill ($NewValue)
setOrder ($NewValue)
setRune ($NewValue)
setType ($NewValue)
getSkill ()
getOrder ()
getRune ()
getType ()
getId ()
save ($HeroId)
Public Attributes
const TABLE = 'comp'
const ID = 'id_comp'
const NOM = 'nomcomp'
const TYPE = 'typecomp'
const TABLE_AFFECTE = 'affecte'
const RUNE = 'rune'
const ORDRE = 'ordre'
const TYPE_ACTIVE = 'active'
const TYPE_PASSIVE = 'passive'
Private Member Functions
fetchId ()
affecte ($HeroId)
Private Attributes
$Id
$Skill
$Order
$Rune
$Type
Detailed Description
Definition at line 7 of file HnSComp.class.php.
Constructor & Destructor Documentation
__construct()
HnsComp::__construct ($Skill = '', $Order = '', $Type = self::TYPE_PASSIVE, $Rune = '')
Hero constructor.
Parameters
int $Hero The position of the player
string $Username The name of the user playing
int $Avatar The avatar of the user
int $Rating The rating of the user
Definition at line 34 of file HnSComp.class.php.
References $Order, $Rune, $Skill, $Type, setOrder(), setRune(), setSkill(), and setType().
Member Function Documentation
__toString()
HnsComp::__toString ()
Definition at line 43 of file HnSComp.class.php.
affecte()
HnsComp::affecte ($HeroId) private
Definition at line 77 of file HnSComp.class.php.
References Hero\ID.
Referenced by save().
fetchId()
HnsComp::fetchId () private
Definition at line 64 of file HnSComp.class.php.
Referenced by getId(), and save().
getId()
HnsComp::getId ()
Definition at line 58 of file HnSComp.class.php.
References $Id, and fetchId().
getOrder()
HnsComp::getOrder ()
Definition at line 54 of file HnSComp.class.php.
References $Order.
getRune()
HnsComp::getRune ()
Definition at line 55 of file HnSComp.class.php.
References $Rune.
getSkill()
HnsComp::getSkill ()
Definition at line 53 of file HnSComp.class.php.
References $Skill.
getType()
HnsComp::getType ()
Definition at line 56 of file HnSComp.class.php.
References $Type.
save()
HnsComp::save ($HeroId)
Definition at line 94 of file HnSComp.class.php.
References affecte(), and fetchId().
setOrder()
HnsComp::setOrder ($NewValue)
Definition at line 49 of file HnSComp.class.php.
Referenced by __construct().
setRune()
HnsComp::setRune ($NewValue)
Definition at line 50 of file HnSComp.class.php.
Referenced by __construct().
setSkill()
HnsComp::setSkill ($NewValue)
Definition at line 48 of file HnSComp.class.php.
Referenced by __construct().
setType()
HnsComp::setType ($NewValue)
Definition at line 51 of file HnSComp.class.php.
Referenced by __construct().
Member Data Documentation
$Id
HnsComp::$Id private
Definition at line 21 of file HnSComp.class.php.
Referenced by getId().
$Order
HnsComp::$Order private
Definition at line 23 of file HnSComp.class.php.
Referenced by __construct(), and getOrder().
$Rune
HnsComp::$Rune private
Definition at line 24 of file HnSComp.class.php.
Referenced by __construct(), and getRune().
$Skill
HnsComp::$Skill private
Definition at line 22 of file HnSComp.class.php.
Referenced by __construct(), and getSkill().
$Type
HnsComp::$Type private
Definition at line 25 of file HnSComp.class.php.
Referenced by __construct(), and getType().
ID
const HnsComp::ID = 'id_comp'
Definition at line 10 of file HnSComp.class.php.
NOM
const HnsComp::NOM = 'nomcomp'
Definition at line 11 of file HnSComp.class.php.
ORDRE
const HnsComp::ORDRE = 'ordre'
Definition at line 16 of file HnSComp.class.php.
RUNE
const HnsComp::RUNE = 'rune'
Definition at line 15 of file HnSComp.class.php.
TABLE
const HnsComp::TABLE = 'comp'
Definition at line 9 of file HnSComp.class.php.
TABLE_AFFECTE
const HnsComp::TABLE_AFFECTE = 'affecte'
Definition at line 14 of file HnSComp.class.php.
TYPE
const HnsComp::TYPE = 'typecomp'
Definition at line 12 of file HnSComp.class.php.
TYPE_ACTIVE
const HnsComp::TYPE_ACTIVE = 'active'
Definition at line 18 of file HnSComp.class.php.
TYPE_PASSIVE
const HnsComp::TYPE_PASSIVE = 'passive'
Definition at line 19 of file HnSComp.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/HnS/HnSComp.class.php