TAGED: PageHnSParse Class Reference
PageHnSParse Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const PARSER_FILE = 'parser_file'
const PARSER_SUBMIT = 'parser_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
parse ()
Protected Attributes
$FileToParse
Detailed Description
Definition at line 8 of file PageHnSParse.class.php.
Constructor & Destructor Documentation
__construct()
PageHnSParse::__construct ($InputData = NULL)
Constructeur de la classe PageHnSParse.
Parameters
mixed $InputData Les données d'entrée pour la page.
Definition at line 25 of file PageHnSParse.class.php.
References $Data, and handle().
Member Function Documentation
handle()
PageHnSParse::handle ($Data) protected
Gère les actions en fonction des données d'entrée.
Parameters
mixed $Data Les données d'entrée pour le traitement.
Definition at line 42 of file PageHnSParse.class.php.
References $Data, parse(), and show().
Referenced by __construct().
parse()
PageHnSParse::parse () protected
Parse le contenu du fichier spécifié et affiche le résultat du parsing.
Definition at line 78 of file PageHnSParse.class.php.
References $Parser, and $TextToParse.
Referenced by handle().
show()
PageHnSParse::show () protected
Affiche le contenu de la page.
Definition at line 67 of file PageHnSParse.class.php.
References $File.
Referenced by handle().
Member Data Documentation
$FileToParse
string null PageHnSParse::$FileToParse protected
Propriété représentant le nom du fichier à parser.
Definition at line 105 of file PageHnSParse.class.php.
PARSER_FILE
const PageHnSParse::PARSER_FILE = 'parser_file'
Nom de la propriété représentant le nom du fichier à parser.
Definition at line 13 of file PageHnSParse.class.php.
PARSER_SUBMIT
const PageHnSParse::PARSER_SUBMIT = 'parser_submit'
Nom de la propriété représentant le bouton de soumission pour le parsing.
Definition at line 18 of file PageHnSParse.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageHnSParse.class.php