TAGED: HnSParser Class Reference
HnSParser Class Reference
Public Member Functions
__construct ($TextToParse, $URL='', $Srv="eu", $HClass="barbarian")
__destruct ()
__toString ()
parse ()
Protected Member Functions
applyPattern ($Pattern, $Callback, $Count=1)
parseHero ($Matches)
parseHeroData ($Matches)
Private Member Functions
clean ()
Private Attributes
$filename
$head
$text
$FullText
$ProcessedText
$Game
$Server
$HeroClass
$URL
$BaseURL
Detailed Description
Definition at line 11 of file HnSParser.class.php.
Constructor & Destructor Documentation
__construct()
HnSParser::__construct ($TextToParse, $URL = '', $Srv = "eu", $HClass = "barbarian")
Constructeur de la classe HnSParser.
Initialise l'objet en utilisant les données de texte à analyser, l'URL, le serveur et la classe de héros fournis.
Parameters
string $TextToParse Les données de texte à analyser pour Hack'N Slash (Diablo 3).
string $URL L'URL associée aux données de texte (facultatif).
string $Srv Le serveur sur lequel le ladder est généré (par défaut : "eu").
string $HClass La classe des héros répertoriés (par défaut : "barbarian").
Definition at line 24 of file HnSParser.class.php.
References $TextToParse, $URL, and clean().
__destruct()
HnSParser::__destruct ()
Destructeur de la classe HnSParser.
Ce destructeur ne contient aucune action spécifique, mais est inclus pour des raisons de cohérence.
Definition at line 42 of file HnSParser.class.php.
Member Function Documentation
__toString()
HnSParser::__toString ()
Méthode magique __toString.
Retourne une chaîne de caractères représentant l'objet lorsqu'il est converti en chaîne.
Returns
string Une chaîne représentant l'objet HnSParser.
Definition at line 53 of file HnSParser.class.php.
applyPattern()
HnSParser::applyPattern ($Pattern, $Callback, $Count = 1) protected
Applique un modèle PCRE (Perl Compatible Regular Expression) à la variable membre $this->ProcessedText.
Cette méthode est utilisée pour appliquer le modèle PCRE à la variable membre $this->ProcessedText, en utilisant la fonction de rappel (callback) fournie.
Parameters
string $Pattern Le modèle PCRE à appliquer.
callable $Callback La fonction de rappel (callback) à utiliser pour le remplacement.
int $Count Le nombre de fois que le modèle PCRE doit être appliqué (par défaut : 1).
Definition at line 89 of file HnSParser.class.php.
clean()
HnSParser::clean () private
Nettoie la variable membre $this->FullText de tous les caractères indésirables.
Cette méthode utilise la modification de motif PCRE m (PCRE_MULTILINE) pour utiliser les caractères "\n" dans une chaîne de sujet afin de faire correspondre les groupes multilignes (particulièrement utile pour les listes).
Definition at line 67 of file HnSParser.class.php.
Referenced by __construct().
parse()
HnSParser::parse ()
Analyse (avec PCRE) la variable membre $this->ProcessedText.
Cette méthode utilise les expressions régulières PCRE pour analyser la variable membre $this->ProcessedText. Elle effectue une série de remplacements et d'actions pour extraire les informations pertinentes des données.
Exceptions
Exception Si une exception se produit lors de l'analyse.
Definition at line 108 of file HnSParser.class.php.
References $ProcessedText.
parseHero()
HnSParser::parseHero ($Matches) protected
Fonction de rappel (callback) pour l'analyse des héros.
Cette méthode est utilisée comme fonction de rappel (callback) par la méthode parse() pour analyser les données d'un héros spécifique à partir du texte analysé.
Parameters
array $Matches Un tableau de correspondances PCRE (résultat de l'analyse).
Returns
string Retourne une chaîne vide, car elle ne remplace pas le texte analysé.
Definition at line 127 of file HnSParser.class.php.
parseHeroData()
HnSParser::parseHeroData ($Matches) protected
Fonction de rappel (callback) pour l'analyse des données d'un héros.
Cette méthode est utilisée comme fonction de rappel (callback) par la méthode parseHero() pour analyser les données spécifiques d'un héros à partir des correspondances PCRE.
Parameters
array $Matches Un tableau de correspondances PCRE (résultat de l'analyse).
Returns
string Retourne une chaîne vide, car elle ne remplace pas le texte analysé.
Definition at line 145 of file HnSParser.class.php.
References Hero\mark4DL().
Member Data Documentation
$BaseURL
HnSParser::$BaseURL private
Definition at line 207 of file HnSParser.class.php.
$filename
HnSParser::$filename private
Definition at line 162 of file HnSParser.class.php.
$FullText
HnSParser::$FullText private
Definition at line 177 of file HnSParser.class.php.
$Game
HnSParser::$Game private
Definition at line 187 of file HnSParser.class.php.
$head
HnSParser::$head private
Definition at line 167 of file HnSParser.class.php.
$HeroClass
HnSParser::$HeroClass private
Definition at line 197 of file HnSParser.class.php.
$ProcessedText
HnSParser::$ProcessedText private
Definition at line 182 of file HnSParser.class.php.
Referenced by parse().
$Server
HnSParser::$Server private
Definition at line 192 of file HnSParser.class.php.
$text
HnSParser::$text private
Definition at line 172 of file HnSParser.class.php.
$URL
HnSParser::$URL private
Definition at line 202 of file HnSParser.class.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
taged/application/src/parse/HnSParser.class.php