TAGED: PageShowAggregate Class Reference
PageShowAggregate Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const SHOW_AGGREGATE = 'change_aggregate'
const SHOW_PASSWORD = 'change_password'
const SHOW_SUBMIT = 'change_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
Protected Attributes
$Result
$Password
$Aggregate
$AggregateObj
$AggregateListObj
$AggregateList
Detailed Description
Definition at line 8 of file PageShowAggregate.class.php.
Constructor & Destructor Documentation
__construct()
PageShowAggregate::__construct ($InputData = NULL)
Initialise l'objet PageShowAggregate.
Parameters
mixed $InputData Les données d'entrée pour initialiser la page. Si null, les données $_REQUEST seront utilisées.
Definition at line 36 of file PageShowAggregate.class.php.
References $Data, and handle().
Member Function Documentation
handle()
PageShowAggregate::handle ($Data) protected
Gère la soumission du formulaire et traite les données d'entrée.
Parameters
mixed $Data Les données d'entrée à traiter.
Definition at line 59 of file PageShowAggregate.class.php.
References $Data, $Password, and show().
Referenced by __construct().
show()
PageShowAggregate::show () protected
Affiche le contenu de la page.
Definition at line 85 of file PageShowAggregate.class.php.
References $Aggregate, $Password, and $Result.
Referenced by handle().
Member Data Documentation
$Aggregate
PageShowAggregate::$Aggregate protected
Definition at line 129 of file PageShowAggregate.class.php.
Referenced by show().
$AggregateList
PageShowAggregate::$AggregateList protected
Definition at line 150 of file PageShowAggregate.class.php.
$AggregateListObj
PageShowAggregate::$AggregateListObj protected
Definition at line 143 of file PageShowAggregate.class.php.
$AggregateObj
PageShowAggregate::$AggregateObj protected
Definition at line 136 of file PageShowAggregate.class.php.
$Password
PageShowAggregate::$Password protected
Definition at line 122 of file PageShowAggregate.class.php.
Referenced by handle(), and show().
$Result
PageShowAggregate::$Result protected
Definition at line 115 of file PageShowAggregate.class.php.
Referenced by show().
SHOW_AGGREGATE
const PageShowAggregate::SHOW_AGGREGATE = 'change_aggregate'
Definition at line 15 of file PageShowAggregate.class.php.
Referenced by PageGestAggregate\show().
SHOW_PASSWORD
const PageShowAggregate::SHOW_PASSWORD = 'change_password'
Definition at line 22 of file PageShowAggregate.class.php.
SHOW_SUBMIT
const PageShowAggregate::SHOW_SUBMIT = 'change_submit'
Definition at line 29 of file PageShowAggregate.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageShowAggregate.class.php