TAGED: Hero Class Reference
Hero Class Reference
Public Member Functions
__construct ($Hero='', $Username='', $URL='', $Rank=9999, $Rift=0, $Time='')
Hero constructor.
__toString ()
setAttr ($Label, $NewValue)
setResources ($NewValue)
setTime ($NewValue)
setId ($NewValue)
setHeroname ($NewValue)
setURL ($NewValue)
setServer ($NewValue)
setClass ($NewValue)
setRank ($NewValue)
setRift ($NewValue)
setLevel ($NewValue)
setParangon ($NewValue)
addComp ($NewValue)
addItem ($NewValue)
addAffix ($NewValue)
setFor ($NewValue)
setDex ($NewValue)
setIntel ($NewValue)
setVita ($NewValue)
setDegats ($NewValue)
setRobustesse ($NewValue)
setRegen ($NewValue)
setRessource1 ($NewValue)
setRessource2 ($NewValue)
setVie ($NewValue)
getHeroname ()
getURL ()
getServer ()
getClass ()
getRank ()
getRift ()
getTime ()
getLevel ()
getParangon ()
getFor ()
getDex ()
getIntel ()
getVita ()
getDegats ()
getRobustesse ()
getRegen ()
getRessource1 ()
getRessource2 ()
getVie ()
getPlayer ()
getItems ()
getCurItem ()
getItem ($ItemId)
getComps ()
getId ()
showAsTableEntry ()
save ()
Static Public Member Functions
static mark4DL ($Array, $BaseURL, $Server, $HeroClass)
static showTableHeader ()
static showTableFooter ()
static getStats ()
Public Attributes
const VIEW = 'vw_hero'
const VIEW_STAT = 'vw_hns_stat'
const TABLE = 'perso'
const ID = 'id_perso'
const NOM = 'nomperso'
const SERVER = 'serveur'
const RANK = 'rang'
const RIFT = 'faille'
const TIME = 'tempsfaille'
const CLASSE = 'classe'
const LEVEL = 'niveau'
const PARANGON = 'parangon'
const FOR = 'force'
const DEX = 'dexterite'
const INTEL = 'intelligence'
const VITA = 'vitalite'
const DEGATS = 'degats'
const ROBUSTESSE = 'robustesse'
const REGEN = 'recuperation'
const VIE = 'vie'
const RES1 = 'ressource_principale'
const RES2 = 'ressource_secondaire'
const ATTR_FOR = 'Strength'
const ATTR_DEX = 'Dexterity'
const ATTR_INTEL = 'Intelligence'
const ATTR_VITA = 'Vitality'
const ATTR_DEGATS = 'Damage'
const ATTR_ROBUSTESSE = 'Toughness'
const ATTR_REGEN = 'Recovery'
const ATTR_VIE = 'Life'
const ATTR_RES_B = 'Fury'
const ATTR_RES_W = 'Arcane Power'
const ATTR_RES_N = 'Essence'
const ATTR_RES_WD = 'Mana'
const ATTR_RES_C = 'Wrath'
const ATTR_RES_M = 'Spirit'
const ATTR_RES_DH = 'Hatred/ Discipline'
const COUNT_HERO = 'count_perso'
const COUNT_TRAD
Private Member Functions
fetchId ()
saveComps ()
saveItems ()
Private Attributes
$Id
$Heroname
$Player
$URL
$Server
$Class
$Rank
$Rift
$TimeStr
$Time
$Level
$Parangon
$For
$Dex
$Intel
$Vita
$Degats
$Robustesse
$Regen
$Ressource1
$Ressource2
$Vie
$Comps
$Items
$CurrentItem
Detailed Description
Definition at line 7 of file Hero.class.php.
Constructor & Destructor Documentation
__construct()
Hero::__construct ($Hero = '', $Username = '', $URL = '', $Rank = 9999, $Rift = 0, $Time = '')
Hero constructor.
Parameters
int $Hero The position of the player
string $Username The name of the user playing
int $Avatar The avatar of the user
int $Rating The rating of the user
Definition at line 89 of file Hero.class.php.
References $Rank, $Rift, $Time, $URL, setHeroname(), and setTime().
Member Function Documentation
__toString()
Hero::__toString ()
Definition at line 139 of file Hero.class.php.
References $Result.
addAffix()
Hero::addAffix ($NewValue)
Definition at line 218 of file Hero.class.php.
References $CurrentItem.
Referenced by HnSHeroParser\parseParams().
addComp()
Hero::addComp ($NewValue)
Definition at line 216 of file Hero.class.php.
Referenced by HnSHeroParser\parseAct(), and HnSHeroParser\parsePass().
addItem()
Hero::addItem ($NewValue)
Definition at line 217 of file Hero.class.php.
References $CurrentItem.
Referenced by HnSHeroParser\parseItem().
fetchId()
Hero::fetchId () private
Definition at line 305 of file Hero.class.php.
References HnSPlayer\ID.
Referenced by getId(), and save().
getClass()
Hero::getClass ()
Definition at line 234 of file Hero.class.php.
References $Class.
getComps()
Hero::getComps ()
Definition at line 257 of file Hero.class.php.
References $Comps.
getCurItem()
Hero::getCurItem ()
Definition at line 254 of file Hero.class.php.
References $CurrentItem.
getDegats()
Hero::getDegats ()
Definition at line 245 of file Hero.class.php.
References $Degats.
getDex()
Hero::getDex ()
Definition at line 242 of file Hero.class.php.
References $Dex.
getFor()
Hero::getFor ()
Definition at line 241 of file Hero.class.php.
References $For.
getHeroname()
Hero::getHeroname ()
Definition at line 231 of file Hero.class.php.
References $Heroname.
getId()
Hero::getId ()
Definition at line 259 of file Hero.class.php.
References $Id, and fetchId().
getIntel()
Hero::getIntel ()
Definition at line 243 of file Hero.class.php.
References $Intel.
getItem()
Hero::getItem ($ItemId)
Definition at line 255 of file Hero.class.php.
getItems()
Hero::getItems ()
Definition at line 253 of file Hero.class.php.
References $Items.
getLevel()
Hero::getLevel ()
Definition at line 238 of file Hero.class.php.
References $Level.
getParangon()
Hero::getParangon ()
Definition at line 239 of file Hero.class.php.
References $Parangon.
getPlayer()
Hero::getPlayer ()
Definition at line 252 of file Hero.class.php.
References $Player.
Referenced by HnSHeroParser\parseUserDetails().
getRank()
Hero::getRank ()
Definition at line 235 of file Hero.class.php.
References $Rank.
getRegen()
Hero::getRegen ()
Definition at line 247 of file Hero.class.php.
References $Regen.
getRessource1()
Hero::getRessource1 ()
Definition at line 248 of file Hero.class.php.
References $Ressource1.
getRessource2()
Hero::getRessource2 ()
Definition at line 249 of file Hero.class.php.
References $Ressource2.
getRift()
Hero::getRift ()
Definition at line 236 of file Hero.class.php.
References $Rift.
getRobustesse()
Hero::getRobustesse ()
Definition at line 246 of file Hero.class.php.
References $Robustesse.
getServer()
Hero::getServer ()
Definition at line 233 of file Hero.class.php.
References $Server.
getStats()
static Hero::getStats () static
Definition at line 425 of file Hero.class.php.
getTime()
Hero::getTime ()
Definition at line 237 of file Hero.class.php.
References $Time.
getURL()
Hero::getURL ()
Definition at line 232 of file Hero.class.php.
References $URL.
Referenced by HnSHeroParser\parse().
getVie()
Hero::getVie ()
Definition at line 250 of file Hero.class.php.
References $Vie.
getVita()
Hero::getVita ()
Definition at line 244 of file Hero.class.php.
References $Vita.
mark4DL()
static Hero::mark4DL ($Array, $BaseURL, $Server, $HeroClass) static
Definition at line 116 of file Hero.class.php.
References $Folder, $Rank, $Rift, $Server, $Time, $TimeStr, $URL, and DATA_TMP_HNS_ADDR.
Referenced by HnSParser\parseHeroData().
save()
Hero::save ()
Definition at line 340 of file Hero.class.php.
References $Id, fetchId(), HnSPlayer\ID, saveComps(), and saveItems().
saveComps()
Hero::saveComps () private
Definition at line 324 of file Hero.class.php.
Referenced by save().
saveItems()
Hero::saveItems () private
Definition at line 332 of file Hero.class.php.
Referenced by save().
setAttr()
Hero::setAttr ($Label, $NewValue)
Definition at line 158 of file Hero.class.php.
References setDegats(), setDex(), setFor(), setIntel(), setRegen(), setResources(), setRessource1(), setRobustesse(), setVie(), and setVita().
Referenced by HnSHeroParser\parseAttrP(), HnSHeroParser\parseAttrR(), and HnSHeroParser\parseAttrS().
setClass()
Hero::setClass ($NewValue)
Definition at line 211 of file Hero.class.php.
Referenced by HnSHeroParser\__construct().
setDegats()
Hero::setDegats ($NewValue)
Definition at line 224 of file Hero.class.php.
Referenced by setAttr().
setDex()
Hero::setDex ($NewValue)
Definition at line 221 of file Hero.class.php.
Referenced by setAttr().
setFor()
Hero::setFor ($NewValue)
Definition at line 220 of file Hero.class.php.
Referenced by setAttr().
setHeroname()
Hero::setHeroname ($NewValue)
Definition at line 208 of file Hero.class.php.
Referenced by __construct(), and HnSHeroParser\parseHero().
setId()
Hero::setId ($NewValue)
Definition at line 207 of file Hero.class.php.
setIntel()
Hero::setIntel ($NewValue)
Definition at line 222 of file Hero.class.php.
Referenced by setAttr().
setLevel()
Hero::setLevel ($NewValue)
Definition at line 214 of file Hero.class.php.
Referenced by HnSHeroParser\parseHero().
setParangon()
Hero::setParangon ($NewValue)
Definition at line 215 of file Hero.class.php.
Referenced by HnSHeroParser\parseHero().
setRank()
Hero::setRank ($NewValue)
Definition at line 212 of file Hero.class.php.
Referenced by HnSHeroParser\__construct().
setRegen()
Hero::setRegen ($NewValue)
Definition at line 226 of file Hero.class.php.
Referenced by setAttr().
setResources()
Hero::setResources ($NewValue)
Definition at line 186 of file Hero.class.php.
References setRessource1(), and setRessource2().
Referenced by setAttr().
setRessource1()
Hero::setRessource1 ($NewValue)
Definition at line 227 of file Hero.class.php.
Referenced by setAttr(), and setResources().
setRessource2()
Hero::setRessource2 ($NewValue)
Definition at line 228 of file Hero.class.php.
Referenced by setResources().
setRift()
Hero::setRift ($NewValue)
Definition at line 213 of file Hero.class.php.
Referenced by HnSHeroParser\__construct().
setRobustesse()
Hero::setRobustesse ($NewValue)
Definition at line 225 of file Hero.class.php.
Referenced by setAttr().
setServer()
Hero::setServer ($NewValue)
Definition at line 210 of file Hero.class.php.
Referenced by HnSHeroParser\__construct().
setTime()
Hero::setTime ($NewValue)
Definition at line 193 of file Hero.class.php.
References $Time.
Referenced by HnSHeroParser\__construct(), and __construct().
setURL()
Hero::setURL ($NewValue)
Definition at line 209 of file Hero.class.php.
Referenced by HnSHeroParser\__construct(), and HnSHeroParser\parseUserDetails().
setVie()
Hero::setVie ($NewValue)
Definition at line 229 of file Hero.class.php.
Referenced by setAttr().
setVita()
Hero::setVita ($NewValue)
Definition at line 223 of file Hero.class.php.
Referenced by setAttr().
showAsTableEntry()
Hero::showAsTableEntry ()
Definition at line 288 of file Hero.class.php.
showTableFooter()
static Hero::showTableFooter () static
Definition at line 283 of file Hero.class.php.
Referenced by HnSTable\show().
showTableHeader()
static Hero::showTableHeader () static
Definition at line 266 of file Hero.class.php.
Referenced by HnSTable\show().
Member Data Documentation
$Class
Hero::$Class private
Definition at line 60 of file Hero.class.php.
Referenced by getClass().
$Comps
Hero::$Comps private
Definition at line 78 of file Hero.class.php.
Referenced by getComps().
$CurrentItem
Hero::$CurrentItem private
Definition at line 80 of file Hero.class.php.
Referenced by addAffix(), addItem(), and getCurItem().
$Degats
Hero::$Degats private
Definition at line 71 of file Hero.class.php.
Referenced by getDegats().
$Dex
Hero::$Dex private
Definition at line 68 of file Hero.class.php.
Referenced by getDex().
$For
Hero::$For private
Definition at line 67 of file Hero.class.php.
Referenced by getFor().
$Heroname
Hero::$Heroname private
Definition at line 56 of file Hero.class.php.
Referenced by getHeroname().
$Id
Hero::$Id private
Definition at line 55 of file Hero.class.php.
Referenced by getId(), and save().
$Intel
Hero::$Intel private
Definition at line 69 of file Hero.class.php.
Referenced by getIntel().
$Items
Hero::$Items private
Definition at line 79 of file Hero.class.php.
Referenced by getItems().
$Level
Hero::$Level private
Definition at line 65 of file Hero.class.php.
Referenced by getLevel().
$Parangon
Hero::$Parangon private
Definition at line 66 of file Hero.class.php.
Referenced by getParangon().
$Player
Hero::$Player private
Definition at line 57 of file Hero.class.php.
Referenced by getPlayer().
$Rank
Hero::$Rank private
Definition at line 61 of file Hero.class.php.
Referenced by __construct(), getRank(), and mark4DL().
$Regen
Hero::$Regen private
Definition at line 73 of file Hero.class.php.
Referenced by getRegen().
$Ressource1
Hero::$Ressource1 private
Definition at line 74 of file Hero.class.php.
Referenced by getRessource1().
$Ressource2
Hero::$Ressource2 private
Definition at line 75 of file Hero.class.php.
Referenced by getRessource2().
$Rift
Hero::$Rift private
Definition at line 62 of file Hero.class.php.
Referenced by __construct(), getRift(), and mark4DL().
$Robustesse
Hero::$Robustesse private
Definition at line 72 of file Hero.class.php.
Referenced by getRobustesse().
$Server
Hero::$Server private
Definition at line 59 of file Hero.class.php.
Referenced by getServer(), and mark4DL().
$Time
Hero::$Time private
Definition at line 64 of file Hero.class.php.
Referenced by __construct(), getTime(), mark4DL(), and setTime().
$TimeStr
Hero::$TimeStr private
Definition at line 63 of file Hero.class.php.
Referenced by mark4DL().
$URL
Hero::$URL private
Definition at line 58 of file Hero.class.php.
Referenced by __construct(), getURL(), and mark4DL().
$Vie
Hero::$Vie private
Definition at line 76 of file Hero.class.php.
Referenced by getVie().
$Vita
Hero::$Vita private
Definition at line 70 of file Hero.class.php.
Referenced by getVita().
ATTR_DEGATS
const Hero::ATTR_DEGATS = 'Damage'
Definition at line 37 of file Hero.class.php.
ATTR_DEX
const Hero::ATTR_DEX = 'Dexterity'
Definition at line 34 of file Hero.class.php.
ATTR_FOR
const Hero::ATTR_FOR = 'Strength'
Definition at line 33 of file Hero.class.php.
ATTR_INTEL
const Hero::ATTR_INTEL = 'Intelligence'
Definition at line 35 of file Hero.class.php.
ATTR_REGEN
const Hero::ATTR_REGEN = 'Recovery'
Definition at line 39 of file Hero.class.php.
ATTR_RES_B
const Hero::ATTR_RES_B = 'Fury'
Definition at line 41 of file Hero.class.php.
ATTR_RES_C
const Hero::ATTR_RES_C = 'Wrath'
Definition at line 45 of file Hero.class.php.
ATTR_RES_DH
const Hero::ATTR_RES_DH = 'Hatred/ Discipline'
Definition at line 47 of file Hero.class.php.
ATTR_RES_M
const Hero::ATTR_RES_M = 'Spirit'
Definition at line 46 of file Hero.class.php.
ATTR_RES_N
const Hero::ATTR_RES_N = 'Essence'
Definition at line 43 of file Hero.class.php.
ATTR_RES_W
const Hero::ATTR_RES_W = 'Arcane Power'
Definition at line 42 of file Hero.class.php.
ATTR_RES_WD
const Hero::ATTR_RES_WD = 'Mana'
Definition at line 44 of file Hero.class.php.
ATTR_ROBUSTESSE
const Hero::ATTR_ROBUSTESSE = 'Toughness'
Definition at line 38 of file Hero.class.php.
ATTR_VIE
const Hero::ATTR_VIE = 'Life'
Definition at line 40 of file Hero.class.php.
ATTR_VITA
const Hero::ATTR_VITA = 'Vitality'
Definition at line 36 of file Hero.class.php.
CLASSE
const Hero::CLASSE = 'classe'
Definition at line 18 of file Hero.class.php.
Referenced by HnSTable\getHeros().
COUNT_HERO
const Hero::COUNT_HERO = 'count_perso'
Definition at line 49 of file Hero.class.php.
COUNT_TRAD
const Hero::COUNT_TRAD
Initial value:
= array (
        self::COUNT_HERO => 'Hros'
    )
Definition at line 51 of file Hero.class.php.
DEGATS
const Hero::DEGATS = 'degats'
Definition at line 25 of file Hero.class.php.
Referenced by HnSTable\getHeros().
DEX
const Hero::DEX = 'dexterite'
Definition at line 22 of file Hero.class.php.
Referenced by HnSTable\getHeros().
FOR
const Hero::FOR = 'force'
Definition at line 21 of file Hero.class.php.
Referenced by HnSTable\getHeros().
ID
const Hero::ID = 'id_perso'
Definition at line 12 of file Hero.class.php.
Referenced by HnsComp\affecte(), HnSTable\getHeros(), and HnsItem\porte().
INTEL
const Hero::INTEL = 'intelligence'
Definition at line 23 of file Hero.class.php.
Referenced by HnSTable\getHeros().
LEVEL
const Hero::LEVEL = 'niveau'
Definition at line 19 of file Hero.class.php.
Referenced by HnSTable\getHeros().
NOM
const Hero::NOM = 'nomperso'
Definition at line 13 of file Hero.class.php.
Referenced by HnSTable\getHeros().
PARANGON
const Hero::PARANGON = 'parangon'
Definition at line 20 of file Hero.class.php.
Referenced by HnSTable\getHeros().
RANK
const Hero::RANK = 'rang'
Definition at line 15 of file Hero.class.php.
Referenced by HnSTable\getHeros().
REGEN
const Hero::REGEN = 'recuperation'
Definition at line 27 of file Hero.class.php.
Referenced by HnSTable\getHeros().
RES1
const Hero::RES1 = 'ressource_principale'
Definition at line 29 of file Hero.class.php.
Referenced by HnSTable\getHeros().
RES2
const Hero::RES2 = 'ressource_secondaire'
Definition at line 30 of file Hero.class.php.
Referenced by HnSTable\getHeros().
RIFT
const Hero::RIFT = 'faille'
Definition at line 16 of file Hero.class.php.
Referenced by HnSTable\getHeros().
ROBUSTESSE
const Hero::ROBUSTESSE = 'robustesse'
Definition at line 26 of file Hero.class.php.
Referenced by HnSTable\getHeros().
SERVER
const Hero::SERVER = 'serveur'
Definition at line 14 of file Hero.class.php.
Referenced by HnSTable\getHeros().
TABLE
const Hero::TABLE = 'perso'
Definition at line 11 of file Hero.class.php.
TIME
const Hero::TIME = 'tempsfaille'
Definition at line 17 of file Hero.class.php.
Referenced by HnSTable\getHeros().
VIE
const Hero::VIE = 'vie'
Definition at line 28 of file Hero.class.php.
Referenced by HnSTable\getHeros().
VIEW
const Hero::VIEW = 'vw_hero'
Definition at line 9 of file Hero.class.php.
Referenced by HnSTable\getHeros().
VIEW_STAT
const Hero::VIEW_STAT = 'vw_hns_stat'
Definition at line 10 of file Hero.class.php.
VITA
const Hero::VITA = 'vitalite'
Definition at line 24 of file Hero.class.php.
Referenced by HnSTable\getHeros().
The documentation for this class was generated from the following file:
taged/application/src/models/HnS/Hero.class.php