TAGED: HnSPlayer Class Reference
HnSPlayer Class Reference
Public Member Functions
__construct ($Username='', $Tag='', $Clan='')
Hero constructor.
__toString ()
setId ($NewValue)
setUsername ($NewValue)
setTag ($NewValue)
setClan ($NewValue)
getUsername ()
getTag ()
getClan ()
getId ()
save ()
Public Attributes
const TABLE = 'joueur'
const ID = 'id_joueur'
const NOM = 'nom'
const TAG = 'tag'
const CLAN = 'clan'
Private Member Functions
fetchId ()
Private Attributes
$Id
$Username
$Tag
$Clan
Detailed Description
Definition at line 7 of file HnSPlayer.class.php.
Constructor & Destructor Documentation
__construct()
HnSPlayer::__construct ($Username = '', $Tag = '', $Clan = '')
Hero constructor.
Parameters
int $Hero The position of the player
string $Username The name of the user playing
int $Avatar The avatar of the user
int $Rating The rating of the user
Definition at line 28 of file HnSPlayer.class.php.
References $Clan, $Tag, $Username, setClan(), setTag(), and setUsername().
Member Function Documentation
__toString()
HnSPlayer::__toString ()
Definition at line 35 of file HnSPlayer.class.php.
References $Tag.
fetchId()
HnSPlayer::fetchId () private
Definition at line 55 of file HnSPlayer.class.php.
Referenced by getId(), and save().
getClan()
HnSPlayer::getClan ()
Definition at line 47 of file HnSPlayer.class.php.
References $Clan.
getId()
HnSPlayer::getId ()
Definition at line 49 of file HnSPlayer.class.php.
References $Id, and fetchId().
getTag()
HnSPlayer::getTag ()
Definition at line 46 of file HnSPlayer.class.php.
References $Tag.
getUsername()
HnSPlayer::getUsername ()
Definition at line 45 of file HnSPlayer.class.php.
References $Username.
save()
HnSPlayer::save ()
Definition at line 71 of file HnSPlayer.class.php.
References fetchId().
setClan()
HnSPlayer::setClan ($NewValue)
Definition at line 43 of file HnSPlayer.class.php.
Referenced by __construct().
setId()
HnSPlayer::setId ($NewValue)
Definition at line 40 of file HnSPlayer.class.php.
setTag()
HnSPlayer::setTag ($NewValue)
Definition at line 42 of file HnSPlayer.class.php.
Referenced by __construct().
setUsername()
HnSPlayer::setUsername ($NewValue)
Definition at line 41 of file HnSPlayer.class.php.
Referenced by __construct().
Member Data Documentation
$Clan
HnSPlayer::$Clan private
Definition at line 19 of file HnSPlayer.class.php.
Referenced by __construct(), and getClan().
$Id
HnSPlayer::$Id private
Definition at line 16 of file HnSPlayer.class.php.
Referenced by getId().
$Tag
HnSPlayer::$Tag private
Definition at line 18 of file HnSPlayer.class.php.
Referenced by __construct(), __toString(), and getTag().
$Username
HnSPlayer::$Username private
Definition at line 17 of file HnSPlayer.class.php.
Referenced by __construct(), and getUsername().
CLAN
const HnSPlayer::CLAN = 'clan'
Definition at line 14 of file HnSPlayer.class.php.
Referenced by HnSTable\getHeros().
ID
const HnSPlayer::ID = 'id_joueur'
Definition at line 11 of file HnSPlayer.class.php.
Referenced by Hero\fetchId(), HnSTable\getHeros(), and Hero\save().
NOM
const HnSPlayer::NOM = 'nom'
Definition at line 12 of file HnSPlayer.class.php.
Referenced by HnSTable\getHeros().
TABLE
const HnSPlayer::TABLE = 'joueur'
Definition at line 10 of file HnSPlayer.class.php.
TAG
const HnSPlayer::TAG = 'tag'
Definition at line 13 of file HnSPlayer.class.php.
Referenced by HnSTable\getHeros().
The documentation for this class was generated from the following file:
taged/application/src/models/HnS/HnSPlayer.class.php