TAGED: CollTable Class Reference
CollTable Class Reference
Public Member Functions
__construct ()
__destruct ()
__toString ()
show ()
Static Public Member Functions
static getStats ()
Public Attributes
const VIEW_STAT = 'vw_coll_stat'
const COUNT_POKEMON = 'count_pokemon'
const COUNT_EQUIPE = 'count_equipe'
const COUNT_COMBAT = 'count_combat'
const COUNT_UTILISATEUR = 'count_utilisateur'
const COUNT_TRAD
Protected Member Functions
getGames ()
Protected Attributes
$ListeCombats
Detailed Description
Definition at line 7 of file CollTable.class.php.
Constructor & Destructor Documentation
__construct()
CollTable::__construct ()
Definition at line 27 of file CollTable.class.php.
References getGames().
__destruct()
CollTable::__destruct ()
Definition at line 35 of file CollTable.class.php.
Member Function Documentation
__toString()
CollTable::__toString ()
Definition at line 44 of file CollTable.class.php.
getGames()
CollTable::getGames () protected
Definition at line 81 of file CollTable.class.php.
References $Result, CollGame\CLASSE, CollGame\ID, CollGame\RESULT, CollGame\RULES, CollGame\TABLE, and CollGame\TIER.
Referenced by __construct().
getStats()
static CollTable::getStats () static
Definition at line 101 of file CollTable.class.php.
show()
CollTable::show ()
Definition at line 68 of file CollTable.class.php.
References CollGame\showTableFooter(), and CollGame\showTableHeader().
Member Data Documentation
$ListeCombats
CollTable::$ListeCombats protected
Definition at line 23 of file CollTable.class.php.
COUNT_COMBAT
const CollTable::COUNT_COMBAT = 'count_combat'
Definition at line 13 of file CollTable.class.php.
COUNT_EQUIPE
const CollTable::COUNT_EQUIPE = 'count_equipe'
Definition at line 12 of file CollTable.class.php.
COUNT_POKEMON
const CollTable::COUNT_POKEMON = 'count_pokemon'
Definition at line 11 of file CollTable.class.php.
COUNT_TRAD
const CollTable::COUNT_TRAD
Initial value:
= array (
        self::COUNT_POKEMON => 'Pokemons',
        self::COUNT_EQUIPE => '&Eacute;quipes',
        self::COUNT_COMBAT => 'Combats',
        self::COUNT_UTILISATEUR => 'Utilisateurs',
    )
Definition at line 16 of file CollTable.class.php.
COUNT_UTILISATEUR
const CollTable::COUNT_UTILISATEUR = 'count_utilisateur'
Definition at line 14 of file CollTable.class.php.
VIEW_STAT
const CollTable::VIEW_STAT = 'vw_coll_stat'
Definition at line 9 of file CollTable.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/Coll/CollTable.class.php