TAGED: PageShowSkyCube Class Reference
PageShowSkyCube Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const SHOW_AGGREGATE = 'sskc_aggregate'
const SHOW_PASSWORD = 'sskc_password'
const SHOW_SUBMIT = 'sskc_submit'
const SHOW_TEST = 'sskc_test'
const SHOW_INPUT = 'sskc_input'
const SHOW_ESPACE = 'sskc_espace'
const SHOW_ACCORDS = 'sskc_accords'
const SHOW_DATACUBE = 'sskc_skycube'
const SHOW_SKYCUBE = 'sskc_sc_red'
const SHOW_TAGED_CUBE = 'sskc_sc_tag'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
Protected Attributes
$SkyCube
$Password
$Aggregate
$AggregateObj
$Test
$ShowInput
$ShowEspace
$ShowAccords
$ShowDataCube
$ShowSkyCube
$ShowTagedCube
$AggregateListObj
$AggregateList
Detailed Description
Definition at line 8 of file PageShowSkyCube.class.php.
Constructor & Destructor Documentation
__construct()
PageShowSkyCube::__construct ($InputData = NULL)
Initialise l'objet PageShowSkyCube.
Parameters
mixed $InputData Les données d'entrée pour initialiser la page. Si null, les données $_REQUEST seront utilisées.
Definition at line 85 of file PageShowSkyCube.class.php.
References $Data, and handle().
Member Function Documentation
handle()
PageShowSkyCube::handle ($Data) protected
Gère la soumission du formulaire et traite les données d'entrée.
Parameters
mixed $Data Les données d'entrée à traiter.
Definition at line 108 of file PageShowSkyCube.class.php.
References $Data, $Password, show(), and Cuboide\TO_MIN.
Referenced by __construct().
show()
PageShowSkyCube::show () protected
Affiche le contenu de la page.
Definition at line 142 of file PageShowSkyCube.class.php.
References $Aggregate, $Password, $Result, SKDisplay\htmlInputData(), SKDisplay\htmlMultidimensionalSpace(), SKDisplay\htmlSkyCubeParam(), SKDisplay\SHOW_DATA_COMPUTED, SKDisplay\SHOW_DATA_FILTERED, SKDisplay\SHOW_DATA_RAW, SKDisplay\SHOW_EQUIV_CLASS, SKDisplay\SHOW_FILTERED, and SKDisplay\SHOW_REMOVED.
Referenced by handle().
Member Data Documentation
$Aggregate
PageShowSkyCube::$Aggregate protected
Definition at line 229 of file PageShowSkyCube.class.php.
Referenced by show().
$AggregateList
PageShowSkyCube::$AggregateList protected
Definition at line 299 of file PageShowSkyCube.class.php.
$AggregateListObj
PageShowSkyCube::$AggregateListObj protected
Definition at line 292 of file PageShowSkyCube.class.php.
$AggregateObj
PageShowSkyCube::$AggregateObj protected
Definition at line 236 of file PageShowSkyCube.class.php.
$Password
PageShowSkyCube::$Password protected
Definition at line 222 of file PageShowSkyCube.class.php.
Referenced by handle(), and show().
$ShowAccords
PageShowSkyCube::$ShowAccords protected
Definition at line 264 of file PageShowSkyCube.class.php.
$ShowDataCube
PageShowSkyCube::$ShowDataCube protected
Definition at line 271 of file PageShowSkyCube.class.php.
$ShowEspace
PageShowSkyCube::$ShowEspace protected
Definition at line 257 of file PageShowSkyCube.class.php.
$ShowInput
PageShowSkyCube::$ShowInput protected
Definition at line 250 of file PageShowSkyCube.class.php.
$ShowSkyCube
PageShowSkyCube::$ShowSkyCube protected
Definition at line 278 of file PageShowSkyCube.class.php.
$ShowTagedCube
PageShowSkyCube::$ShowTagedCube protected
Definition at line 285 of file PageShowSkyCube.class.php.
$SkyCube
PageShowSkyCube::$SkyCube protected
Definition at line 215 of file PageShowSkyCube.class.php.
$Test
PageShowSkyCube::$Test protected
Definition at line 243 of file PageShowSkyCube.class.php.
SHOW_ACCORDS
const PageShowSkyCube::SHOW_ACCORDS = 'sskc_accords'
Definition at line 57 of file PageShowSkyCube.class.php.
SHOW_AGGREGATE
const PageShowSkyCube::SHOW_AGGREGATE = 'sskc_aggregate'
Definition at line 15 of file PageShowSkyCube.class.php.
SHOW_DATACUBE
const PageShowSkyCube::SHOW_DATACUBE = 'sskc_skycube'
Definition at line 64 of file PageShowSkyCube.class.php.
SHOW_ESPACE
const PageShowSkyCube::SHOW_ESPACE = 'sskc_espace'
Definition at line 50 of file PageShowSkyCube.class.php.
SHOW_INPUT
const PageShowSkyCube::SHOW_INPUT = 'sskc_input'
Definition at line 43 of file PageShowSkyCube.class.php.
SHOW_PASSWORD
const PageShowSkyCube::SHOW_PASSWORD = 'sskc_password'
Definition at line 22 of file PageShowSkyCube.class.php.
SHOW_SKYCUBE
const PageShowSkyCube::SHOW_SKYCUBE = 'sskc_sc_red'
Definition at line 71 of file PageShowSkyCube.class.php.
SHOW_SUBMIT
const PageShowSkyCube::SHOW_SUBMIT = 'sskc_submit'
Definition at line 29 of file PageShowSkyCube.class.php.
SHOW_TAGED_CUBE
const PageShowSkyCube::SHOW_TAGED_CUBE = 'sskc_sc_tag'
Definition at line 78 of file PageShowSkyCube.class.php.
SHOW_TEST
const PageShowSkyCube::SHOW_TEST = 'sskc_test'
Definition at line 36 of file PageShowSkyCube.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageShowSkyCube.class.php