TAGED: SkyCubeEmergent Class Reference
SkyCubeEmergent Class Reference
Public Member Functions
__construct ($Data, $RelationCols, $MeasureCols, $MinMax=Cuboide::TO_MAX, $ComputeAccordCuboides=FALSE)
getCuboides ()
getCuboide ($ID)
getCuboideIDs ($Filtered=TRUE)
getMultidimensionalSpace ()
getEmergence ()
getCodedColumnName ($FullName)
getFullColumnName ($CodedName)
getDenumberedColIDs ()
getSkyCube1 ()
getSkyCube2 ()
setEmergenceRatio ($CuboideID, $MeasureID, $Relation, $EmergenceRatio)
Public Member Functions inherited from SkyCube
__construct ($Data, $RelationCols, $MeasureCols, $MinMax=Cuboide::TO_MAX, $ComputeAccordCuboides=FALSE)
testCombinatorial ()
getMultidimensionalSpace ()
getDataSet ()
getRowHeaders ()
getColIDs ()
getCuboides ()
getCuboideIDs ($Filtered=TRUE)
getCuboide ($ID)
Public Attributes
const SKYCUBE = 'SkyCubeBlocNestedLoop'
Public Attributes inherited from SkyCube
const MAX_CUBOIDE = 128
const MIN_COLID = 'A'
const CUBOIDE = 'Cuboide'
Protected Member Functions
getColID ($ColHeader, $MeasureCols)
computeDataSet ($Data, $RelationCols, $MeasureCols)
mergeCuboideLists ()
Protected Member Functions inherited from SkyCube
generateCuboideListLvl ($Level, $ColIDs, $ComputeAccordCuboides=FALSE, $Current='')
generateCuboideList ($ComputeAccordCuboides=FALSE)
getColID ($ColHeader, $MeasureCols)
computeDataSet ($Data, $RelationCols, $MeasureCols)
generateCombinatorial ($List, $Begin=array())
Protected Attributes
$SkyCube1
$SkyCube2
$ComputeAccordCuboides
$DenumberedColIDs
$Emergence
Protected Attributes inherited from SkyCube
$DataSet
$RowHeaders
$ColIDs
$MinMax
$IsValid
$CurrentColID
$SetsOfParts
$Cuboides
$OrderedCuboideIDs
$FilteredCuboideIDs
Detailed Description
Definition at line 9 of file SkyCubeEmergent.class.php.
Constructor & Destructor Documentation
__construct()
SkyCubeEmergent::__construct ($Data, $RelationCols, $MeasureCols, $MinMax = Cuboide::TO_MAX, $ComputeAccordCuboides = FALSE)
Constructeur de la classe SkyCubeEmergent.
Parameters
array $Data Les données brutes à utiliser dans l'espace multidimensionnel.
array $RelationCols Les colonnes d'identification de relation.
array $MeasureCols Les colonnes d'identification d'attribut (mesure).
int $MinMax Indicateur pour la valeur maximale ou minimale lors de la construction des Cuboides.
bool $ComputeAccordCuboides Indicateur pour calculer les Cuboides en accord.
Definition at line 25 of file SkyCubeEmergent.class.php.
References $ComputeAccordCuboides, $Data, SkyCube\$MinMax, and computeDataSet().
Member Function Documentation
computeDataSet()
SkyCubeEmergent::computeDataSet ($Data, $RelationCols, $MeasureCols) protected
Méthode protégée pour calculer le DataSet à partir des données brutes, des colonnes de relation et des colonnes d'attribut.
Parameters
array $Data Les données brutes à utiliser dans l'espace multidimensionnel.
array $RelationCols Les colonnes d'identification de relation.
array $MeasureCols Les colonnes d'identification d'attribut (mesure).
Definition at line 95 of file SkyCubeEmergent.class.php.
References $Data, and mergeCuboideLists().
Referenced by __construct().
getCodedColumnName()
SkyCubeEmergent::getCodedColumnName ($FullName)
Méthode pour obtenir le nom de colonne encodé à partir du nom complet.
Parameters
string $FullName Le nom complet de la colonne encodée.
Returns
string Le nom de colonne encodé.
Definition at line 284 of file SkyCubeEmergent.class.php.
getColID()
SkyCubeEmergent::getColID ($ColHeader, $MeasureCols) protected
Méthode protégée pour obtenir l'ID d'une colonne.
Parameters
string $ColHeader Le nom de la colonne.
array $MeasureCols Les colonnes d'identification d'attribut (mesure).
Returns
string L'ID de la colonne.
Definition at line 46 of file SkyCubeEmergent.class.php.
References SkyCube\$CurrentColID.
getCuboide()
SkyCubeEmergent::getCuboide ($ID)
Méthode pour obtenir un Cuboide spécifique en fonction de son ID.
Parameters
string $ID L'ID du Cuboide recherché.
Returns
CuboideEmergent|null Le Cuboide correspondant à l'ID ou NULL si non trouvé.
Definition at line 205 of file SkyCubeEmergent.class.php.
Referenced by getCuboideIDs().
getCuboideIDs()
SkyCubeEmergent::getCuboideIDs ($Filtered = TRUE)
Méthode pour obtenir les IDs des Cuboides, filtrés ou non, indexés par leur niveau et leur ID.
Parameters
bool $Filtered Indicateur pour obtenir les Cuboides filtrés ou non.
Returns
array Les IDs des Cuboides, filtrés ou non, indexés par leur niveau et leur ID.
Definition at line 232 of file SkyCubeEmergent.class.php.
References SkyCube\$Cuboides, and getCuboide().
getCuboides()
SkyCubeEmergent::getCuboides ()
Méthode pour obtenir la liste des Cuboides du SkyCubeEmergent.
Returns
array La liste des Cuboides du SkyCubeEmergent.
Definition at line 177 of file SkyCubeEmergent.class.php.
References SkyCube\$Cuboides.
getDenumberedColIDs()
SkyCubeEmergent::getDenumberedColIDs ()
Méthode pour obtenir la liste des identifiants de colonnes dénumérotées.
Returns
array La liste des identifiants de colonnes dénumérotées.
Definition at line 305 of file SkyCubeEmergent.class.php.
References $DenumberedColIDs.
getEmergence()
SkyCubeEmergent::getEmergence ()
Méthode pour obtenir l'ensemble des informations d'émergence.
Returns
array L'ensemble des informations d'émergence.
Definition at line 273 of file SkyCubeEmergent.class.php.
References $Emergence.
getFullColumnName()
SkyCubeEmergent::getFullColumnName ($CodedName)
Méthode pour obtenir le nom complet d'une colonne à partir du nom de colonne encodé.
Parameters
string $CodedName Le nom de colonne encodé.
Returns
string Le nom complet de la colonne.
Definition at line 295 of file SkyCubeEmergent.class.php.
Referenced by setEmergenceRatio().
getMultidimensionalSpace()
SkyCubeEmergent::getMultidimensionalSpace ()
Méthode pour obtenir l'espace multidimensionnel généré par le SkyCubeEmergent.
Returns
array L'espace multidimensionnel.
Definition at line 263 of file SkyCubeEmergent.class.php.
getSkyCube1()
SkyCubeEmergent::getSkyCube1 ()
Méthode pour obtenir le premier SkyCube utilisé dans le SkyCubeEmergent.
Returns
SkyCube Le premier SkyCube utilisé dans le SkyCubeEmergent.
Definition at line 315 of file SkyCubeEmergent.class.php.
References $SkyCube1.
getSkyCube2()
SkyCubeEmergent::getSkyCube2 ()
Méthode pour obtenir le deuxième SkyCube utilisé dans le SkyCubeEmergent.
Returns
SkyCube Le deuxième SkyCube utilisé dans le SkyCubeEmergent.
Definition at line 325 of file SkyCubeEmergent.class.php.
References $SkyCube2.
mergeCuboideLists()
SkyCubeEmergent::mergeCuboideLists () protected
Méthode protégée pour fusionner les listes de Cuboides de SkyCube1 et SkyCube2.
Definition at line 148 of file SkyCubeEmergent.class.php.
Referenced by computeDataSet().
setEmergenceRatio()
SkyCubeEmergent::setEmergenceRatio ($CuboideID, $MeasureID, $Relation, $EmergenceRatio)
Méthode pour définir le ratio d'émergence pour un Cuboide spécifique.
Parameters
string $CuboideID L'ID du Cuboide pour lequel définir le ratio d'émergence.
string $MeasureID L'ID de la mesure concernée.
array $Relation Les identifiants de relation pour le Cuboide.
float $EmergenceRatio Le ratio d'émergence à définir.
Definition at line 338 of file SkyCubeEmergent.class.php.
References getFullColumnName().
Member Data Documentation
$ComputeAccordCuboides
SkyCubeEmergent::$ComputeAccordCuboides protected
Definition at line 373 of file SkyCubeEmergent.class.php.
Referenced by __construct().
$DenumberedColIDs
SkyCubeEmergent::$DenumberedColIDs protected
Definition at line 380 of file SkyCubeEmergent.class.php.
Referenced by getDenumberedColIDs().
$Emergence
SkyCubeEmergent::$Emergence protected
Definition at line 387 of file SkyCubeEmergent.class.php.
Referenced by getEmergence().
$SkyCube1
SkyCubeEmergent::$SkyCube1 protected
Definition at line 359 of file SkyCubeEmergent.class.php.
Referenced by getSkyCube1().
$SkyCube2
SkyCubeEmergent::$SkyCube2 protected
Definition at line 366 of file SkyCubeEmergent.class.php.
Referenced by getSkyCube2().
SKYCUBE
const SkyCubeEmergent::SKYCUBE = 'SkyCubeBlocNestedLoop'
Le nom de la classe Skycube utilisée pour la construction des SkyCubes internes.
Definition at line 14 of file SkyCubeEmergent.class.php.
The documentation for this class was generated from the following file:
taged/application/src/algo/SkyCubeEmergent.class.php