TAGED: Cuboide Class Reference
Cuboide Class Reference
Public Member Functions
__construct ($CuboideID, $RawDataSet, $RawRowHeaders, $RawColIDs, $MinMax=self::TO_MAX)
computeCuboide ()
Public Attributes
const TO_MAX = 'max'
const TO_MIN = 'min'
const TEST_ON = self::TO_MAX
const CURRENT = ''
Protected Member Functions
computeDataSet ($RawDataSet, $RawColIDs)
isInCuboide ($ConsideredRowID)
Protected Attributes
$MinMax
Detailed Description
Definition at line 7 of file Cuboide.class.php.
Constructor & Destructor Documentation
__construct()
Cuboide::__construct ($CuboideID, $RawDataSet, $RawRowHeaders, $RawColIDs, $MinMax = self::TO_MAX)
Cuboide constructor.
Parameters
string $CuboideID The Cuboide ID.
array $RawDataSet The raw data set.
array $RawRowHeaders The raw row headers.
array $RawColIDs The raw column IDs.
string $MinMax The minimum or maximum value type (TO_MAX or TO_MIN).
Definition at line 25 of file Cuboide.class.php.
References $MinMax, and computeDataSet().
Member Function Documentation
computeCuboide()
Cuboide::computeCuboide ()
Computes the Cuboide.
Definition at line 103 of file Cuboide.class.php.
References isInCuboide().
computeDataSet()
Cuboide::computeDataSet ($RawDataSet, $RawColIDs) protected
Prepares the data set
Removes empty lines Computes Accords classes
Parameters
array $RawDataSet
array $RawColIDs
Definition at line 43 of file Cuboide.class.php.
Referenced by __construct().
isInCuboide()
Cuboide::isInCuboide ($ConsideredRowID) protected
Checks if a given row is in the Cuboide.
Parameters
mixed $ConsideredRowID The row ID to consider.
Returns
bool Returns true if the row is in the Cuboide, otherwise false.
Definition at line 123 of file Cuboide.class.php.
Referenced by computeCuboide().
Member Data Documentation
$MinMax
Cuboide::$MinMax protected
Definition at line 128 of file Cuboide.class.php.
Referenced by __construct().
CURRENT
const Cuboide::CURRENT = ''
Definition at line 14 of file Cuboide.class.php.
TEST_ON
const Cuboide::TEST_ON = self::TO_MAX
Definition at line 12 of file Cuboide.class.php.
TO_MAX
const Cuboide::TO_MAX = 'max'
Definition at line 9 of file Cuboide.class.php.
TO_MIN
const Cuboide::TO_MIN = 'min'
Definition at line 10 of file Cuboide.class.php.
Referenced by PageTestAccords\handle(), PageTestSkyCube\handle(), PageTestSkyCubeEmergent\handle(), PageRunSkyCubeAnalysis\handle(), PageShowSkyCube\handle(), and Analysis\prepare().
The documentation for this class was generated from the following file:
taged/application/src/algo/Cuboide.class.php