TAGED: PageNewAggregate Class Reference
PageNewAggregate Class Reference
Public Member Functions
__construct ($InputData=NULL)
Public Member Functions inherited from TagedPage
__construct ($InputData=NULL)
showPageHeader ()
showPageFooter ()
Public Attributes
const NAG_DB = 'nag_game'
const NAG_AGGREGATE = 'nag_aggregate'
const NAG_TABLE = 'nag_table'
const NAG_REL_COLS = 'nag_relation_cols'
const NAG_MES_COLS = 'nag_measure_cols'
const NAG_PASSWORD = 'nag_password'
const NAG_SUBMIT = 'nag_submit'
Public Attributes inherited from TagedPage
const PAGE_SELECTOR = 'sel'
const PAGE_DEFAULT = 'Accueil'
const PAGE_LIST
Protected Member Functions
handle ($Data)
show ()
Protected Attributes
$Games
$Password
$Aggregate
Detailed Description
Definition at line 8 of file PageNewAggregate.class.php.
Constructor & Destructor Documentation
__construct()
PageNewAggregate::__construct ($InputData = NULL)
Constructeur de la classe PageNewAggregate.
Parameters
mixed $InputData Les données d'entrée pour la page.
Definition at line 57 of file PageNewAggregate.class.php.
References $Data, $Games, APP_NAMES, and handle().
Member Function Documentation
handle()
PageNewAggregate::handle ($Data) protected
Gère les données entrées dans le formulaire pour créer une agrégation.
Parameters
mixed $Data Les données du formulaire.
Definition at line 83 of file PageNewAggregate.class.php.
References $Aggregate, $Data, $File, $Games, $Password, PageChangeAggregate\CHANGE_AGGREGATE, Analysis\create(), and show().
Referenced by __construct().
show()
PageNewAggregate::show () protected
Affiche le formulaire pour créer une agrégation de données.
Definition at line 137 of file PageNewAggregate.class.php.
References $Aggregate, $Games, and $Password.
Referenced by handle().
Member Data Documentation
$Aggregate
PageNewAggregate::$Aggregate protected
Definition at line 179 of file PageNewAggregate.class.php.
Referenced by handle(), and show().
$Games
PageNewAggregate::$Games protected
Definition at line 165 of file PageNewAggregate.class.php.
Referenced by __construct(), handle(), and show().
$Password
PageNewAggregate::$Password protected
Definition at line 172 of file PageNewAggregate.class.php.
Referenced by handle(), and show().
NAG_AGGREGATE
const PageNewAggregate::NAG_AGGREGATE = 'nag_aggregate'
Definition at line 20 of file PageNewAggregate.class.php.
NAG_DB
const PageNewAggregate::NAG_DB = 'nag_game'
Definition at line 14 of file PageNewAggregate.class.php.
NAG_MES_COLS
const PageNewAggregate::NAG_MES_COLS = 'nag_measure_cols'
Definition at line 38 of file PageNewAggregate.class.php.
NAG_PASSWORD
const PageNewAggregate::NAG_PASSWORD = 'nag_password'
Definition at line 44 of file PageNewAggregate.class.php.
NAG_REL_COLS
const PageNewAggregate::NAG_REL_COLS = 'nag_relation_cols'
Definition at line 32 of file PageNewAggregate.class.php.
NAG_SUBMIT
const PageNewAggregate::NAG_SUBMIT = 'nag_submit'
Definition at line 50 of file PageNewAggregate.class.php.
NAG_TABLE
const PageNewAggregate::NAG_TABLE = 'nag_table'
Definition at line 26 of file PageNewAggregate.class.php.
The documentation for this class was generated from the following file:
taged/application/src/pages/PageNewAggregate.class.php