TAGED: HnSTable Class Reference
HnSTable Class Reference
Public Member Functions
__construct ()
__destruct ()
__toString ()
show ()
Protected Member Functions
getHeros ()
Protected Attributes
$ListeHeros
Detailed Description
Definition at line 7 of file HnSTable.class.php.
Constructor & Destructor Documentation
__construct()
HnSTable::__construct ()
Definition at line 13 of file HnSTable.class.php.
References getHeros().
__destruct()
HnSTable::__destruct ()
Definition at line 21 of file HnSTable.class.php.
Member Function Documentation
__toString()
HnSTable::__toString ()
Definition at line 30 of file HnSTable.class.php.
getHeros()
HnSTable::getHeros () protected
Definition at line 50 of file HnSTable.class.php.
References $Result, HnSPlayer\CLAN, Hero\CLASSE, Hero\DEGATS, Hero\DEX, Hero\FOR, HnSPlayer\ID, Hero\ID, Hero\INTEL, Hero\LEVEL, HnSPlayer\NOM, Hero\NOM, Hero\PARANGON, Hero\RANK, Hero\REGEN, Hero\RES1, Hero\RES2, Hero\RIFT, Hero\ROBUSTESSE, Hero\SERVER, HnSPlayer\TAG, Hero\TIME, Hero\VIE, Hero\VIEW, and Hero\VITA.
Referenced by __construct().
show()
HnSTable::show ()
Definition at line 37 of file HnSTable.class.php.
References Hero\showTableFooter(), and Hero\showTableHeader().
Member Data Documentation
$ListeHeros
HnSTable::$ListeHeros protected
Definition at line 9 of file HnSTable.class.php.
The documentation for this class was generated from the following file:
taged/application/src/models/HnS/HnSTable.class.php