TAGED: SkyCube Class Reference
SkyCube Class Reference
Public Member Functions
__construct ($Data, $RelationCols, $MeasureCols, $MinMax=Cuboide::TO_MAX, $ComputeAccordCuboides=FALSE)
testCombinatorial ()
getMultidimensionalSpace ()
getDataSet ()
getRowHeaders ()
getColIDs ()
getCuboides ()
getCuboideIDs ($Filtered=TRUE)
getCuboide ($ID)
Public Attributes
const MAX_CUBOIDE = 128
const MIN_COLID = 'A'
const CUBOIDE = 'Cuboide'
Protected Member Functions
generateCuboideListLvl ($Level, $ColIDs, $ComputeAccordCuboides=FALSE, $Current='')
generateCuboideList ($ComputeAccordCuboides=FALSE)
getColID ($ColHeader, $MeasureCols)
computeDataSet ($Data, $RelationCols, $MeasureCols)
generateCombinatorial ($List, $Begin=array())
Protected Attributes
$DataSet
$RowHeaders
$ColIDs
$MinMax
$IsValid
$CurrentColID
$SetsOfParts
$Cuboides
$OrderedCuboideIDs
$FilteredCuboideIDs
Detailed Description
Definition at line 13 of file SkyCube.class.php.
Constructor & Destructor Documentation
__construct()
SkyCube::__construct ($Data, $RelationCols, $MeasureCols, $MinMax = Cuboide::TO_MAX, $ComputeAccordCuboides = FALSE)
Constructeur de la classe SkyCube.
Parameters
array $Data Les données brutes à utiliser dans l'espace multidimensionnel.
array $RelationCols Les colonnes d'identification de relation.
array $MeasureCols Les colonnes d'identification d'attribut (mesure).
int $MinMax Indicateur pour la valeur maximale ou minimale lors de la construction des Cuboides.
bool $ComputeAccordCuboides Indicateur pour calculer les Cuboides en accord.
Definition at line 39 of file SkyCube.class.php.
References $Data, $MinMax, computeDataSet(), and generateCuboideList().
Member Function Documentation
computeDataSet()
SkyCube::computeDataSet ($Data, $RelationCols, $MeasureCols) protected
Méthode protégée pour calculer le DataSet à partir des données brutes, des colonnes de relation et des colonnes d'attribut.
Parameters
array $Data Les données brutes à utiliser dans l'espace multidimensionnel.
array $RelationCols Les colonnes d'identification de relation.
array $MeasureCols Les colonnes d'identification d'attribut (mesure).
Definition at line 165 of file SkyCube.class.php.
References $Data, and getColID().
Referenced by __construct().
generateCombinatorial()
SkyCube::generateCombinatorial ($List, $Begin = array ()) protected
Méthode protégée pour générer des combinaisons de valeurs.
Parameters
array $List Le tableau de valeurs à combiner.
array $Begin La combinaison actuelle en cours de construction.
Returns
array Les combinaisons générées.
Definition at line 236 of file SkyCube.class.php.
Referenced by getMultidimensionalSpace(), and testCombinatorial().
generateCuboideList()
SkyCube::generateCuboideList ($ComputeAccordCuboides = FALSE) protected
Méthode protégée pour générer la liste des Cuboides pour un niveau donné.
Parameters
int $Level Le niveau du Cuboide.
array $ColIDs Les IDs des colonnes à utiliser pour générer les Cuboides.
bool $ComputeAccordCuboides Indicateur pour calculer les Cuboides en accord.
string $Current La combinaison d'en-têtes actuelle pour le Cuboide.
Definition at line 118 of file SkyCube.class.php.
References generateCuboideListLvl().
Referenced by __construct().
generateCuboideListLvl()
SkyCube::generateCuboideListLvl ($Level, $ColIDs, $ComputeAccordCuboides = FALSE, $Current = '') protected
Méthode protégée pour générer la liste des Cuboides pour un niveau donné.
Parameters
int $Level Le niveau du Cuboide.
array $ColIDs Les IDs des colonnes à utiliser pour générer les Cuboides.
bool $ComputeAccordCuboides Indicateur pour calculer les Cuboides en accord.
string $Current La combinaison d'en-têtes actuelle pour le Cuboide.
Definition at line 68 of file SkyCube.class.php.
References $ColIDs.
Referenced by generateCuboideList().
getColID()
SkyCube::getColID ($ColHeader, $MeasureCols) protected
Méthode protégée pour obtenir l'ID d'une colonne.
Parameters
string $ColHeader Le nom de la colonne.
array $MeasureCols Les colonnes d'identification d'attribut (mesure).
Returns
string L'ID de la colonne.
Definition at line 149 of file SkyCube.class.php.
Referenced by computeDataSet().
getColIDs()
SkyCube::getColIDs ()
Méthode pour obtenir les en-têtes de colonnes (ColIDs) du Skycube.
Returns
array Les en-têtes de colonnes (ColIDs) du Skycube.
Definition at line 362 of file SkyCube.class.php.
References $ColIDs.
Referenced by CoSky\prepare().
getCuboide()
SkyCube::getCuboide ($ID)
Méthode pour obtenir un Cuboide spécifique en fonction de son ID.
Parameters
string $ID L'ID du Cuboide recherché.
Returns
Cuboide|null Le Cuboide correspondant à l'ID ou NULL si non trouvé.
Definition at line 394 of file SkyCube.class.php.
Referenced by Analysis\computeCuboide(), Analysis\computeCuboideAttribute(), Analysis\generateAlgoInput(), and CoSky\prepare().
getCuboideIDs()
SkyCube::getCuboideIDs ($Filtered = TRUE)
Méthode pour obtenir les IDs des Cuboides, filtrés ou non, indexés par leur niveau et leur ID.
Parameters
bool $Filtered Indicateur pour obtenir les Cuboides filtrés ou non.
Returns
array Les IDs des Cuboides, filtrés ou non, indexés par leur niveau et leur ID.
Definition at line 383 of file SkyCube.class.php.
Referenced by Analysis\compute(), Analysis\generateAlgoInput(), and CoSky\prepare().
getCuboides()
SkyCube::getCuboides ()
Méthode pour obtenir la liste des Cuboides du Skycube.
Returns
array La liste des Cuboides du Skycube.
Definition at line 372 of file SkyCube.class.php.
References $Cuboides.
getDataSet()
SkyCube::getDataSet ()
Méthode pour obtenir le DataSet du Skycube.
Returns
array Le DataSet du Skycube.
Definition at line 342 of file SkyCube.class.php.
References $DataSet.
getMultidimensionalSpace()
SkyCube::getMultidimensionalSpace ()
Méthode pour obtenir l'espace multidimensionnel généré par le Skycube.
Returns
array L'espace multidimensionnel.
Definition at line 282 of file SkyCube.class.php.
References generateCombinatorial().
getRowHeaders()
SkyCube::getRowHeaders ()
Méthode pour obtenir les en-têtes de lignes du Skycube.
Returns
array Les en-têtes de lignes du Skycube.
Definition at line 352 of file SkyCube.class.php.
References $RowHeaders.
testCombinatorial()
SkyCube::testCombinatorial ()
Méthode de test pour générer des combinaisons et afficher le résultat. Utilisée uniquement à des fins de test.
Definition at line 266 of file SkyCube.class.php.
References generateCombinatorial().
Member Data Documentation
$ColIDs
SkyCube::$ColIDs protected
Definition at line 418 of file SkyCube.class.php.
Referenced by generateCuboideListLvl(), and getColIDs().
$Cuboides
SkyCube::$Cuboides protected
Definition at line 453 of file SkyCube.class.php.
Referenced by SkyCubeEmergent\getCuboideIDs(), SkyCubeEmergent\getCuboides(), and getCuboides().
$CurrentColID
SkyCube::$CurrentColID protected
Definition at line 439 of file SkyCube.class.php.
Referenced by SkyCubeEmergent\getColID().
$DataSet
SkyCube::$DataSet protected
Definition at line 404 of file SkyCube.class.php.
Referenced by getDataSet().
$FilteredCuboideIDs
SkyCube::$FilteredCuboideIDs protected
Definition at line 467 of file SkyCube.class.php.
$IsValid
SkyCube::$IsValid protected
Definition at line 432 of file SkyCube.class.php.
$MinMax
SkyCube::$MinMax protected
Definition at line 425 of file SkyCube.class.php.
Referenced by SkyCubeEmergent\__construct(), and __construct().
$OrderedCuboideIDs
SkyCube::$OrderedCuboideIDs protected
Definition at line 460 of file SkyCube.class.php.
$RowHeaders
SkyCube::$RowHeaders protected
Definition at line 411 of file SkyCube.class.php.
Referenced by getRowHeaders().
$SetsOfParts
SkyCube::$SetsOfParts protected
Definition at line 446 of file SkyCube.class.php.
CUBOIDE
const SkyCube::CUBOIDE = 'Cuboide'
Le nom de la classe Cuboide utilisée pour la construction des Cuboides.
Definition at line 28 of file SkyCube.class.php.
MAX_CUBOIDE
const SkyCube::MAX_CUBOIDE = 128
Le nombre maximal de Cuboides autorisé.
Definition at line 18 of file SkyCube.class.php.
MIN_COLID
const SkyCube::MIN_COLID = 'A'
L'ID de la première colonne de données.
Definition at line 23 of file SkyCube.class.php.
The documentation for this class was generated from the following file:
taged/application/src/algo/SkyCube.class.php