TAGED: taged/application/script/processHnS.php File Reference
processHnS.php File Reference
Namespaces
TAGED
Variables
$ProcessFolderScr = './processHnSFolder.php'
$Children = array ()
$PoolSize = 2
$Data = scandir (DATA_TMP_HNS_ADDR)
Variable Documentation
$Children
$Children = array ()
Definition at line 10 of file processHnS.php.
$Data
$Data = scandir (DATA_TMP_HNS_ADDR)
Definition at line 17 of file processHnS.php.
Referenced by DisplaySkyCube\__construct(), PageCollAggregate\__construct(), PageTest\__construct(), PageCollData\__construct(), PageTestAccords\__construct(), PageTestCoSky\__construct(), PageTestSkyCube\__construct(), PageTestSkyCubeEmergent\__construct(), PageAccueil\__construct(), PageHnSData\__construct(), PageRunSkyCubeAnalysis\__construct(), WSDefault\__construct(), SkyCubeEmergent\__construct(), PageCollParse\__construct(), PageHnSParse\__construct(), PageGestAggregate\__construct(), PageShowAggregate\__construct(), SkyCube\__construct(), PageChangeAggregate\__construct(), PageNewAggregate\__construct(), PageShowSkyCube\__construct(), PageRunAnalysis\__construct(), PageAccueil\addStat(), PageAccueil\addStats(), Analysis\cleanData(), SkyCubeEmergent\computeDataSet(), SkyCube\computeDataSet(), DisplaySkyCube\computeDataSet(), SKDisplay\computeDataSet(), PageAccueil\computeStatsDB(), PageAccueil\computeStatsFiles(), PageAccueil\doStats(), AggregateList\getFileField(), PageTestCoSky\handle(), PageRunSkyCubeAnalysis\handle(), PageHnSParse\handle(), PageCollParse\handle(), PageGestAggregate\handle(), PageShowAggregate\handle(), PageChangeAggregate\handle(), PageNewAggregate\handle(), PageShowSkyCube\handle(), PageRunAnalysis\handle(), IDEA\interpret(), WSMatch3\newGame(), Analysis\runCuboide(), and WSMatch3\store().
$PoolSize
$PoolSize = 2
Definition at line 11 of file processHnS.php.
$ProcessFolderScr
$ProcessFolderScr = './processHnSFolder.php'
Definition at line 8 of file processHnS.php.