name: GitHub Actions

on: [release]

jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v.1.0
